import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'ka' | 'ru' | 'tr' | 'uk';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Browser language detection helper
const detectBrowserLanguage = (): Language => {
  const supportedLanguages: Language[] = ['en', 'ka', 'ru', 'tr', 'uk'];
  
  // First check localStorage
  const savedLang = localStorage.getItem('preferred-language');
  if (savedLang && supportedLanguages.includes(savedLang as Language)) {
    return savedLang as Language;
  }
  
  // Then check browser language
  const browserLang = navigator.language.split('-')[0].toLowerCase();
  
  // Map browser language codes to our supported languages
  const languageMap: Record<string, Language> = {
    'en': 'en',
    'ka': 'ka',
    'ru': 'ru',
    'tr': 'tr',
    'uk': 'uk',
    'ge': 'ka', // Alternative code for Georgian
  };
  
  return languageMap[browserLang] || 'en';
};

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.rooms': 'Rooms',
    'nav.amenities': 'Amenities',
    'nav.location': 'Location',
    'nav.reviews': 'Reviews',
    'nav.contact': 'Contact',
    'nav.bookNow': 'Book Now',
    'nav.videos': 'Videos',
    'nav.apartments': 'Apartments',
    'nav.loyalty': 'Bonuses',
    'nav.about': 'About Us',
    
    // Index Videos Section
    'index.videos.title': 'Explore Our Property Tours',
    'index.videos.subtitle': 'Watch our latest videos showcasing the beauty and luxury of Orbi City Batumi',
    'index.videos.viewAll': 'View All Videos',
    
    // Hero
    'hero.title': 'Your Perfect Seaside Escape',
    'hero.subtitle': 'Luxury Sea View Apartments in the Heart of Batumi',
    'hero.bookNowPayLater': 'BOOK NOW / PAY LATER',
    'hero.whatsapp': 'WhatsApp',
    
    // Booking Widget
    'booking.title': 'Check Availability',
    'booking.selectDate': 'Select date',
    'booking.checkIn': 'Check In',
    'booking.checkOut': 'Check Out',
    'booking.guests': 'Guests',
    'booking.checkAvailability': 'Check Availability',
    
    // Rooms
    'rooms.title': 'Find Your Perfect Space',
    'rooms.subtitle': 'Each apartment is thoughtfully designed to provide an unparalleled experience',
    'rooms.suite': 'Suite with Sea View',
    'rooms.suiteDesc': 'An elegant suite offering breathtaking views of the sea, perfect for couples or solo travelers',
    'rooms.deluxe': 'Deluxe Suite with Sea View',
    'rooms.deluxeDesc': 'A more spacious and luxurious suite with enhanced amenities and a prime sea view',
    'rooms.superior': 'Superior Suite with Sea View',
    'rooms.superiorDesc': 'Premium suite featuring a separate living area and best panoramic views of the sea',
    'rooms.family': 'Superior Family Suite',
    'rooms.familyDesc': 'Generously sized suite with multiple rooms, perfect for families or groups',
    'rooms.twobed': 'Two Bedroom Panoramic Suite',
    'rooms.twobedDesc': 'The pinnacle of luxury. Expansive suite with two bedrooms and stunning panoramic terrace',
    'rooms.viewDetails': 'View Details',
    'rooms.bookNow': 'Book Now',
    'rooms.from': 'From',
    'rooms.night': '/night',
    'rooms.size': 'Size',
    'rooms.guests': 'Guests',
    'rooms.watchVideo': 'Watch Property Tour',
    
    // Amenities
    'amenities.title': 'World-Class Amenities',
    'amenities.subtitle': 'Everything you need for a perfect stay',
    'amenities.seaView': 'Sea View',
    'amenities.fountains': 'Near Fountains',
    'amenities.kitchen': 'Full Kitchenette',
    'amenities.reception': '24/7 Reception',
    'amenities.pool': 'Swimming Pool',
    'amenities.parking': 'Parking',
    'amenities.wifi': 'High-Speed WiFi',
    'amenities.ac': 'Air Conditioning',
    'amenities.housekeeping': 'Housekeeping',
    'amenities.security': '24/7 Security',
    'amenities.concierge': 'Concierge Service',
    'amenities.restaurant': 'Restaurant',
    
    // Location
    'location.title': 'Prime Location in Batumi',
    'location.subtitle': 'Steps away from the Black Sea and major attractions',
    'location.beach': 'Black Sea Beach',
    'location.beachDist': '50 meters',
    'location.fountains': 'Dancing Fountains',
    'location.fountainsDist': '100 meters',
    'location.airport': 'Batumi Airport',
    'location.airportDist': '5 kilometers',
    
    // Reviews
    'reviews.title': 'Guest Reviews',
    'reviews.subtitle': 'What our guests say about us',
    'reviews.rating': 'Guest Rating',
    'reviews.review1': 'Absolutely stunning views of the Black Sea! The apartment was luxurious and the staff incredibly welcoming.',
    'reviews.review2': 'Perfect location near the beach and fountains. The apartment was spotless and well-equipped.',
    'reviews.review3': 'Amazing experience! The sea view from our balcony was breathtaking. Highly recommend!',
    
    // CTA
    'cta.title': 'Ready to Experience Luxury by the Sea?',
    'cta.subtitle': 'Book your perfect apartment today',
    'cta.button': 'Book Your Stay',
    
    // Footer
    'footer.description': 'Luxury serviced apartments in the heart of Batumi, Georgia. Steps from the Black Sea.',
    'footer.quickLinks': 'Quick Links',
    'footer.contact': 'Contact Us',
    'footer.phone': 'Phone',
    'footer.email': 'Email',
    'footer.address': 'Address',
    'footer.followUs': 'Follow Us',
    'footer.rights': '© 2025 Orbi City Batumi. All rights reserved.',
    
    // Apartments Page
    'apartments.hero.title': 'Luxury Apartments in Batumi',
    'apartments.hero.subtitle': 'Discover our exquisite collection of sea-view apartments, each designed to provide the ultimate comfort and sophistication. From intimate suites to spacious family accommodations.',
    'apartments.section.title': 'Find Your Perfect Space',
    'apartments.section.subtitle': 'Each apartment is thoughtfully designed to provide an unparalleled experience. Explore our offerings and find the one that speaks to you.',
    'apartments.sqm': 'm²',
    'apartments.guests': 'Guests',
    'apartments.bed': 'Bed',
    'apartments.beds': 'Beds',
    'apartments.sofaBed': 'Sofa Bed',
    'apartments.bath': 'Bath',
    'apartments.baths': 'Baths',
    'apartments.bidet': 'Bidet',
    'apartments.keyFeatures': 'Key Features',
    'apartments.bookNow': 'Book Now / Pay Later',
    'apartments.checkAvailability': 'Check Availability',
    
    // Suite
    'apartments.suite.title': 'Suite with Sea View',
    'apartments.suite.desc': 'An elegant suite offering breathtaking panoramic views of the Black Sea. Perfect for couples or solo travelers seeking a tranquil escape with modern amenities and sophisticated design. Wake up to stunning sunrises over the sea from your private balcony.',
    'apartments.suite.feature1': 'Private Sea View Balcony',
    'apartments.suite.feature2': 'Fully Equipped Kitchenette',
    'apartments.suite.feature3': 'High-Speed WiFi',
    'apartments.suite.feature4': 'Smart Climate Control',
    'apartments.suite.feature5': '55" Smart TV with Streaming',
    'apartments.suite.feature6': 'King Size Bed with Premium Linens',
    
    // Deluxe
    'apartments.deluxe.title': 'Deluxe Suite with Sea View',
    'apartments.deluxe.desc': 'A more spacious and luxurious suite featuring enhanced amenities and prime sea views. Designed for discerning guests who appreciate attention to detail and comfort. The separate living area provides additional space for relaxation and entertainment.',
    'apartments.deluxe.feature1': 'Expansive Sea View Balcony',
    'apartments.deluxe.feature2': 'Separate Living & Dining Area',
    'apartments.deluxe.feature3': 'Full Kitchen with Premium Appliances',
    'apartments.deluxe.feature4': 'Complimentary High-Speed WiFi',
    'apartments.deluxe.feature5': 'Dual-Zone Climate Control',
    'apartments.deluxe.feature6': 'Premium Entertainment System',
    
    // Superior
    'apartments.superior.title': 'Superior Suite with Sea View',
    'apartments.superior.desc': 'Our premium suite featuring a separate bedroom, luxurious living area, and the best panoramic views of the Black Sea. Ideal for guests who desire extra space and premium amenities. Corner location ensures maximum natural light and sweeping ocean vistas.',
    'apartments.superior.feature1': 'Corner Panoramic Sea Views',
    'apartments.superior.feature2': 'One Separate Bedroom',
    'apartments.superior.feature3': 'Spacious Dining Area',
    'apartments.superior.feature4': 'Modern Full Bathroom',
    'apartments.superior.feature5': 'Designer Kitchenette',
    'apartments.superior.feature6': 'Luxury Bath Amenities',
    'apartments.superior.feature7': 'King Bed with Ceiling Mirrors',
    
    // Family
    'apartments.family.title': 'Superior Family Suite with Sea View',
    'apartments.family.desc': 'A generously sized suite with two bedrooms and two bathrooms, perfect for families or groups of up to 6 guests. Enjoy comfort and privacy with separate sleeping areas while maintaining connection in the spacious living space. Ideal for creating lasting memories with loved ones.',
    'apartments.family.feature1': 'Expansive Private Balcony',
    'apartments.family.feature2': 'Two Separate Bedrooms',
    'apartments.family.feature3': 'Two Full Bathrooms with Bidet',
    'apartments.family.feature4': 'Full Kitchen & Dining Area',
    'apartments.family.feature5': 'In-Unit Washing Machine',
    'apartments.family.feature6': 'Concierge Priority Services',
    'apartments.family.feature7': 'King Beds with Premium Features',
    
    // Two Bedroom
    'apartments.twobed.title': 'Two Bedroom Panoramic Suite',
    'apartments.twobed.desc': 'The pinnacle of luxury living in Batumi. This expansive suite features two master bedrooms and a spectacular 270° panoramic terrace offering uninterrupted views of the Black Sea. Perfect for families or groups seeking the ultimate in space, comfort, and breathtaking scenery.',
    'apartments.twobed.feature1': '270° Panoramic Ocean Terrace',
    'apartments.twobed.feature2': '2 Master Bedrooms with En-suite',
    'apartments.twobed.feature3': '2 Convertible Sofa Beds',
    'apartments.twobed.feature4': '2 King Beds with Ceiling Mirrors',
    'apartments.twobed.feature5': 'Gourmet Kitchen',
    'apartments.twobed.feature6': 'Designer Luxury Furnishings',
    'apartments.twobed.feature7': 'Ultimate Sea & City Views',
    
    // Location Page
    'location.page.title': 'Prime Seafront Location',
    'location.page.subtitle': 'Perfectly positioned in the heart of Batumi, steps from the Black Sea and major attractions. Experience the best of coastal living with unparalleled convenience.',
    
    // Amenities
    'amenities.hero.title': 'World-Class Amenities',
    'amenities.hero.subtitle': 'Everything you need for an unforgettable stay',
    'amenities.premium.title': 'Premium Facilities',
    'amenities.premium.subtitle': 'Indulge in our exclusive amenities designed for your ultimate comfort',
    'amenities.standard.title': 'Essential Services',
    'amenities.standard.subtitle': 'All the conveniences you expect and more',
    'amenities.pool.title': 'Swimming Pool & Spa',
    'amenities.pool.desc': 'Relax in our stunning infinity pool with panoramic sea views',
    'amenities.fitness.title': 'Fitness Center',
    'amenities.fitness.desc': 'State-of-the-art gym equipment for your workout routine',
    'amenities.spa.title': 'Wellness & Spa',
    'amenities.spa.desc': 'Rejuvenate with our professional spa treatments',
    'amenities.restaurant.title': 'Fine Dining Restaurant',
    'amenities.restaurant.desc': 'Savor exquisite cuisine prepared by world-class chefs',
    'amenities.cafe.title': 'Seaside Café',
    'amenities.cafe.desc': 'Enjoy coffee and light bites with stunning ocean views',
    'amenities.bar.title': 'Rooftop Bar',
    'amenities.bar.desc': 'Unwind with premium cocktails and breathtaking sunset views',
    'amenities.wifi.title': 'High-Speed WiFi',
    'amenities.wifi.desc': 'Complimentary high-speed internet throughout the property',
    'amenities.security.title': '24/7 Security',
    'amenities.security.desc': 'Round-the-clock security and surveillance for your peace of mind',
    'amenities.reception.title': '24/7 Reception',
    'amenities.reception.desc': 'Our concierge team is always at your service',
    'amenities.parking.title': 'Secure Parking',
    'amenities.parking.desc': 'Complimentary parking with 24/7 security',
    'amenities.ac.title': 'Climate Control',
    'amenities.ac.desc': 'Individual air conditioning in every apartment',
    'amenities.concierge.title': 'Concierge Services',
    'amenities.concierge.desc': 'Personalized assistance for all your needs',
    
    // Purchase Conditions
    'purchase.hero.title': 'Purchase & Booking Conditions',
    'purchase.hero.subtitle': 'Clear, transparent terms for your peace of mind',
    'purchase.breadcrumb': 'Purchase Conditions',
    'purchase.payment.title': 'Payment Terms',
    'purchase.payment.content': 'We accept bank transfers, credit/debit cards, and cash. Full payment is required upon check-in unless pre-arranged. We offer flexible payment plans for extended stays. All major credit cards accepted.',
    'purchase.cancellation.title': 'Cancellation Policy',
    'purchase.cancellation.content': 'Free cancellation up to 7 days before arrival. Cancellations within 7 days incur a 50% charge. No-shows result in full charge. We understand plans change - contact us for special circumstances.',
    'purchase.deposit.title': 'Security Deposit',
    'purchase.deposit.content': 'A refundable security deposit may be required upon check-in. The amount varies by apartment type. Deposits are fully refunded after inspection, typically within 3-5 business days.',
    'purchase.refund.title': 'Refund Policy',
    'purchase.refund.content': 'Refunds are processed within 14 business days to your original payment method. Processing fees are non-refundable. For cancellations beyond the free period, partial refunds apply as per our cancellation policy.',
    'purchase.important.title': 'Important Information',
    'purchase.important.point1': 'Valid ID or passport required at check-in',
    'purchase.important.point2': 'Minimum age requirement: 18 years',
    'purchase.important.point3': 'Pets allowed with prior approval (additional fee may apply)',
    'purchase.updated': 'Last updated',
    'purchase.updateDate': 'January 2025',
    
    // Loyalty Program
    'loyalty.hero.title': 'Orbi Rewards Program',
    'loyalty.hero.subtitle': 'Earn points with every stay and unlock exclusive benefits',
    'loyalty.hero.cta': 'Join Now - It\'s Free',
    'loyalty.howItWorks.title': 'How It Works',
    'loyalty.howItWorks.subtitle': 'Start earning rewards in three simple steps',
    'loyalty.step1.title': 'Create Account',
    'loyalty.step1.desc': 'Sign up for free and start earning immediately',
    'loyalty.step2.title': 'Earn Points',
    'loyalty.step2.desc': 'Get 10 points for every GEL spent on bookings',
    'loyalty.step3.title': 'Redeem Rewards',
    'loyalty.step3.desc': 'Use your points for discounts and exclusive perks',
    'loyalty.benefits.title': 'Member Benefits',
    'loyalty.benefits.subtitle': 'Exclusive advantages for our valued members',
    'loyalty.benefit1': 'Early check-in and late checkout when available',
    'loyalty.benefit2': 'Complimentary room upgrades (subject to availability)',
    'loyalty.benefit3': 'Priority booking during peak season',
    'loyalty.benefit4': 'Exclusive member-only rates and promotions',
    'loyalty.benefit5': 'Birthday surprises and anniversary gifts',
    'loyalty.testimonials.title': 'What Our Members Say',
    'loyalty.testimonial1': 'The loyalty program is amazing! I saved over 200 GEL on my last booking and got a free room upgrade!',
    'loyalty.testimonial2': 'Being a member has made my regular trips to Batumi so much better. The perks are real!',
    'loyalty.cta.title': 'Ready to Start Earning?',
    'loyalty.cta.subtitle': 'Join thousands of satisfied members today',
    'loyalty.cta.button': 'Create Free Account',
    
    // About Us
    'about.hero.title': 'About Orbi City Batumi',
    'about.hero.subtitle': 'Your gateway to unforgettable experiences on the Black Sea coast',
    'about.story.title': 'Our Story',
    'about.story.p1': 'Orbi City Batumi represents the pinnacle of modern aparthotel living on Georgia\'s stunning Black Sea coast. Since our inception, we have been dedicated to providing guests with an unparalleled blend of luxury, comfort, and authentic Georgian hospitality.',
    'about.story.p2': 'Strategically located in the heart of Batumi, just 50 meters from the pristine beach and walking distance to the city\'s main attractions, we offer the perfect base for both leisure and business travelers.',
    'about.story.p3': 'Our commitment to excellence is reflected in every detail - from our meticulously designed apartments featuring breathtaking sea views to our world-class amenities and personalized concierge services.',
    'about.mission.title': 'Our Mission',
    'about.mission.desc': 'To provide every guest with an extraordinary experience that exceeds expectations, combining the comfort of home with five-star luxury and authentic Georgian warmth.',
    'about.vision.title': 'Our Vision',
    'about.vision.desc': 'To be recognized as the premier aparthotel destination on the Black Sea coast, setting the standard for hospitality excellence and creating lasting memories for our guests.',
    'about.values.title': 'Our Core Values',
    'about.values.subtitle': 'The principles that guide everything we do',
    'about.value1.title': 'Guest-Centric Excellence',
    'about.value1.desc': 'Every decision we make puts our guests\' satisfaction and comfort first',
    'about.value2.title': 'Quality Without Compromise',
    'about.value2.desc': 'We maintain the highest standards in every aspect of our service',
    'about.value3.title': 'Innovation & Growth',
    'about.value3.desc': 'Continuously evolving to meet and exceed modern travelers\' needs',
    'about.stat1': 'Luxury Apartments',
    'about.stat2': 'Happy Guests',
    'about.stat3': 'Guest Rating',
    'about.stat4': 'Service',
    'about.gallery.title': 'Experience Orbi City',
    
    // Apartment Detail
    'apartmentDetail.notFound': 'Apartment not found',
    'apartmentDetail.backToList': 'Back to Apartments',
    'apartmentDetail.description': 'Description',
    'apartmentDetail.booking': 'Booking',
    'apartmentDetail.watchVideos': 'Watch Videos',
    
    // YouTube Videos
    'youtubeVideos.title': 'Video Gallery',
    'youtubeVideos.subtitle': 'Discover Orbi City Batumi through our videos',
    'youtubeVideos.breadcrumb': 'Videos',
    'youtubeVideos.error': 'Unable to load videos at this moment. Please try again later.',
    'youtubeVideos.noVideos': 'No videos available',
    'youtubeVideos.noDescription': 'Watch this video to learn more',
    'youtubeVideos.watchNow': 'Watch Now',
    'youtubeVideos.featured': 'Featured',
    'youtubeVideos.noVideosInCategory': 'No videos in this category yet',
    'youtubeVideos.category.all': 'All Videos',
    'youtubeVideos.category.propertyTours': 'Property Tours',
    'youtubeVideos.category.testimonials': 'Testimonials',
    'youtubeVideos.category.areaGuide': 'Area Guide',
    'youtubeVideos.category.amenities': 'Amenities',
  },
  ka: {
    // Navigation
    'nav.home': 'მთავარი',
    'nav.rooms': 'ოთახები',
    'nav.amenities': 'სერვისები',
    'nav.location': 'ლოკაცია',
    'nav.reviews': 'მიმოხილვები',
    'nav.contact': 'კონტაქტი',
    'nav.bookNow': 'დაჯავშნე ახლავე',
    'nav.videos': 'ვიდეოები',
    'nav.apartments': 'აპარტამენტები',
    'nav.loyalty': 'ბონუსები',
    'nav.about': 'ჩვენს შესახებ',
    
    // Index Videos Section
    'index.videos.title': 'გაეცანით ჩვენს ობიექტის ტურებს',
    'index.videos.subtitle': 'ნახეთ ჩვენი უახლესი ვიდეოები, რომლებიც წარმოაჩენს Orbi City Batumi-ს სილამაზეს და ფუფუნებას',
    'index.videos.viewAll': 'ყველა ვიდეოს ნახვა',
    
    // Hero
    'hero.title': 'თქვენი იდეალური სანაპირო დასვენება',
    'hero.subtitle': 'ლუქს აპარტამენტები ზღვის ხედით ბათუმის გულში',
    'hero.bookNowPayLater': 'დაჯავშნე ახლა / გადაიხადე მოგვიანებით',
    'hero.whatsapp': 'WhatsApp',
    
    // Booking Widget
    'booking.title': 'დაჯავშნე ახლა',
    'booking.selectDate': 'აირჩიე თარიღი',
    'booking.checkIn': 'დაბინავება',
    'booking.checkOut': 'დატოვება',
    'booking.guests': 'სტუმრები',
    'booking.checkAvailability': 'შეამოწმე ხელმისაწვდომობა',
    
    // Rooms
    'rooms.title': 'იპოვე შენი იდეალური სივრცე',
    'rooms.subtitle': 'თითოეული აპარტამენტი შექმნილია განსაკუთრებული გამოცდილებისთვის',
    'rooms.suite': 'სუიტი ზღვის ხედით',
    'rooms.suiteDesc': 'ელეგანტური სუიტი ზღვის თვალწარმტაცი ხედებით, იდეალური წყვილებისთვის',
    'rooms.deluxe': 'დელუქს სუიტი ზღვის ხედით',
    'rooms.deluxeDesc': 'უფრო ვრცელი და ლუქს სუიტი გაუმჯობესებული სერვისებით',
    'rooms.superior': 'სუპერიორ სუიტი ზღვის ხედით',
    'rooms.superiorDesc': 'პრემიუმ სუიტი ცალკე საცხოვრებელი სივრცით და საუკეთესო პანორამული ხედებით',
    'rooms.family': 'სუპერიორ ოჯახური სუიტი',
    'rooms.familyDesc': 'ვრცელი სუიტი რამდენიმე ოთახით, იდეალური ოჯახებისა და ჯგუფებისთვის',
    'rooms.twobed': 'ორ საძინებლიანი პანორამული სუიტი',
    'rooms.twobedDesc': 'ლუქსის მწვერვალი. ვრცელი სუიტი ორი საძინებლითა და შესანიშნავი პანორამული ტერასით',
    'rooms.viewDetails': 'იხილე დეტალები',
    'rooms.bookNow': 'დაჯავშნე ახლა',
    'rooms.from': 'დან',
    'rooms.night': '/ღამე',
    'rooms.size': 'ზომა',
    'rooms.guests': 'სტუმრები',
    'rooms.watchVideo': 'ობიექტის ტურის ნახვა',
    
    // Amenities
    'amenities.title': 'მსოფლიო დონის სერვისები',
    'amenities.subtitle': 'ყველაფერი რაც გჭირდებათ შესანიშნავი დასვენებისთვის',
    'amenities.seaView': 'ზღვის ხედი',
    'amenities.fountains': 'ახლოს შადრევნებთან',
    'amenities.kitchen': 'სრული სამზარეულო',
    'amenities.reception': '24/7 რეცეფცია',
    'amenities.pool': 'საცურაო აუზი',
    'amenities.parking': 'პარკინგი',
    'amenities.wifi': 'უსადენო ინტერნეტი',
    'amenities.ac': 'კონდიციონერი',
    'amenities.housekeeping': 'დასუფთავება',
    'amenities.security': '24/7 უსაფრთხოება',
    'amenities.concierge': 'კონსიერჟ სერვისი',
    'amenities.restaurant': 'რესტორანი',
    
    // Location
    'location.title': 'პრიმიუმ ლოკაცია ბათუმში',
    'location.subtitle': 'რამდენიმე ნაბიჯით შავი ზღვისა და ძირითადი ღირსშესანიშნაობებიდან',
    'location.beach': 'შავი ზღვის პლაჟი',
    'location.beachDist': '50 მეტრი',
    'location.fountains': 'მომღერალი შადრევნები',
    'location.fountainsDist': '100 მეტრი',
    'location.airport': 'ბათუმის აეროპორტი',
    'location.airportDist': '5 კილომეტრი',
    
    // Reviews
    'reviews.title': 'სტუმრების მიმოხილვები',
    'reviews.subtitle': 'რას ამბობენ ჩვენი სტუმრები',
    'reviews.rating': 'სტუმრების შეფასება',
    'reviews.review1': 'შესანიშნავი ხედები შავ ზღვაზე! აპარტამენტი იყო ლუქსუსური და პერსონალი უზომოდ თბილი.',
    'reviews.review2': 'სრულყოფილი ლოკაცია პლაჟთან და შადრევნებთან ახლოს. აპარტამენტი სუფთა და კარგად აღჭურვილი.',
    'reviews.review3': 'საოცარი გამოცდილება! ზღვის ხედი ბალკონიდან თვალწარმტაცი იყო. ძალიან გირჩევთ!',
    
    // CTA
    'cta.title': 'მზად ხართ განსაკუთრებული გამოცდილებისთვის?',
    'cta.subtitle': 'დაჯავშნეთ თქვენი იდეალური აპარტამენტი დღეს',
    'cta.button': 'დაჯავშნე ახლა',
    
    // Footer
    'footer.description': 'ლუქს სერვისული აპარტამენტები ბათუმის გულში, საქართველო. შავი ზღვის პირას.',
    'footer.quickLinks': 'სწრაფი ბმულები',
    'footer.contact': 'დაგვიკავშირდით',
    'footer.phone': 'ტელეფონი',
    'footer.email': 'ელ-ფოსტა',
    'footer.address': 'მისამართი',
    'footer.followUs': 'გამოგვყევით',
    'footer.rights': '© 2025 ორბი სითი ბათუმი. ყველა უფლება დაცულია.',
    
    // Apartments Page
    'apartments.hero.title': 'ლუქს აპარტამენტები ბათუმში',
    'apartments.hero.subtitle': 'აღმოაჩინეთ ზღვის ხედით აპარტამენტების განსაკუთრებული კოლექცია, თითოეული შექმნილია მაქსიმალური კომფორტისა და განსაკუთრებულობისთვის. ინტიმური სუიტებიდან ვრცელ ოჯახურ საცხოვრებლებამდე.',
    'apartments.section.title': 'იპოვეთ თქვენი იდეალური სივრცე',
    'apartments.section.subtitle': 'თითოეული აპარტამენტი შექმნილია განსაკუთრებული გამოცდილებისთვის. იკვლიეთ ჩვენი შეთავაზებები და იპოვეთ ის, რაც თქვენთვის შესაფერისია.',
    'apartments.sqm': 'კვ.მ.',
    'apartments.guests': 'სტუმარი',
    'apartments.bed': 'საწოლი',
    'apartments.beds': 'საწოლი',
    'apartments.sofaBed': 'დივანი',
    'apartments.bath': 'აბაზანა',
    'apartments.baths': 'აბაზანა',
    'apartments.bidet': 'ბიდე',
    'apartments.keyFeatures': 'ძირითადი მახასიათებლები',
    'apartments.bookNow': 'დაჯავშნე ახლა / გადაიხადე მოგვიანებით',
    'apartments.checkAvailability': 'შეამოწმე ხელმისაწვდომობა',
    
    // Suite
    'apartments.suite.title': 'სუიტი ზღვის ხედით',
    'apartments.suite.desc': 'ელეგანტური სუიტი შავი ზღვის თვალწარმტაცი პანორამული ხედებით. იდეალურია წყვილებისთვის ან მოგზაურებისთვის, რომლებიც ეძებენ მშვიდ თავშესაფარს თანამედროვე სიახლეებით. გამოეღვიძეთ შემაგდებელი განთიადისგან თქვენი პირადი აივნიდან.',
    'apartments.suite.feature1': 'პირადი აივანი ზღვის ხედით',
    'apartments.suite.feature2': 'სრულად აღჭურვილი მინი სამზარეულო',
    'apartments.suite.feature3': 'მაღალსიჩქარიანი WiFi',
    'apartments.suite.feature4': 'ჭკვიანი კლიმატკონტროლი',
    'apartments.suite.feature5': '55" Smart TV სტრიმინგით',
    'apartments.suite.feature6': 'King Size საწოლი პრემიუმ თეთრეულით',
    
    // Deluxe
    'apartments.deluxe.title': 'დელუქს სუიტი ზღვის ხედით',
    'apartments.deluxe.desc': 'უფრო ვრცელი და ლუქსუზური სუიტი გაუმჯობესებული სერვისებით და პრიმიუმ ზღვის ხედებით. შექმნილია მომთხოვნი სტუმრებისთვის, რომლებიც აფასებენ დეტალებზე ყურადღებას და კომფორტს. ცალკე სამ სივრცე უზრუნველყოფს დამატებით ადგილს დასასვენებლად.',
    'apartments.deluxe.feature1': 'ვრცელი აივანი ზღვის ხედით',
    'apartments.deluxe.feature2': 'ცალკე საცხოვრებელი და სასადილო',
    'apartments.deluxe.feature3': 'სრული სამზარეულო პრემიუმ ტექნიკით',
    'apartments.deluxe.feature4': 'უფასო მაღალსიჩქარიანი WiFi',
    'apartments.deluxe.feature5': 'ორზონიანი კლიმატკონტროლი',
    'apartments.deluxe.feature6': 'პრემიუმ გასართობი სისტემა',
    
    // Superior
    'apartments.superior.title': 'სუპერიორ სუიტი ზღვის ხედით',
    'apartments.superior.desc': 'ჩვენი პრემიუმ სუიტი ცალკე საძინებლით, ლუქსუზური საცხოვრებელი სივრცით და შავი ზღვის საუკეთესო პანორამული ხედებით. იდეალურია სტუმრებისთვის, რომლებსაც სურთ დამატებითი სივრცე და პრემიუმ სერვისები. კუთხური მდებარეობა უზრუნველყოფს მაქსიმალურ ბუნებრივ სინათლეს.',
    'apartments.superior.feature1': 'კუთხური პანორამული ზღვის ხედები',
    'apartments.superior.feature2': 'ერთი ცალკე საძინებელი',
    'apartments.superior.feature3': 'ვრცელი სასადილო ზონა',
    'apartments.superior.feature4': 'თანამედროვე სრული აბაზანა',
    'apartments.superior.feature5': 'დიზაინერული მინი სამზარეულო',
    'apartments.superior.feature6': 'ლუქს აბაზანის აქსესუარები',
    'apartments.superior.feature7': 'King Size საწოლი ჭერის სარკეებით',
    
    // Family
    'apartments.family.title': 'სუპერიორ ოჯახური სუიტი ზღვის ხედით',
    'apartments.family.desc': 'ვრცელი სუიტი ორი საძინებლით და ორი აბაზანით, იდეალურია ოჯახებისთვის ან 6 სტუმრამდე ჯგუფებისთვის. ისიამოვნეთ კომფორტით და კონფიდენციალურობით ცალკე საძინებლებით, ვრცელ საცხოვრებელ სივრცეში კავშირის შენარჩუნებით. იდეალურია საყვარელებთან დაუვიწყარი მოგონებების შესაქმნელად.',
    'apartments.family.feature1': 'ვრცელი პირადი აივანი',
    'apartments.family.feature2': 'ორი ცალკე საძინებელი',
    'apartments.family.feature3': 'ორი სრული აბაზანა ბიდეთით',
    'apartments.family.feature4': 'სრული სამზარეულო და სასადილო ზონა',
    'apartments.family.feature5': 'სარეცხი მანქანა',
    'apartments.family.feature6': 'კონსიერჟის პრიორიტეტული სერვისები',
    'apartments.family.feature7': 'King Size საწოლები პრემიუმ ფუნქციებით',
    
    // Two Bedroom
    'apartments.twobed.title': 'ორ საძინებლიანი პანორამული სუიტი',
    'apartments.twobed.desc': 'ლუქსის მწვერვალი ბათუმში. ეს ვრცელი სუიტი შეიცავს ორ მასტერ საძინებელს და სანახაობრივ 270° პანორამულ ტერასას შავი ზღვის შეუფერხებელი ხედებით. იდეალურია ოჯახებისთვის ან ჯგუფებისთვის, რომლებიც ეძებენ სივრცის, კომფორტისა და თვალწარმტაცი პეიზაჟის ულტიმატს.',
    'apartments.twobed.feature1': '270° პანორამული ოკეანის ტერასა',
    'apartments.twobed.feature2': '2 მასტერ საძინებელი ინდივიდუალური აბაზანებით',
    'apartments.twobed.feature3': '2 გარდასაქმნელი დივანი',
    'apartments.twobed.feature4': '2 King Size საწოლი ჭერის სარკეებით',
    'apartments.twobed.feature5': 'გურმანული სამზარეულო',
    'apartments.twobed.feature6': 'დიზაინერული ლუქს მებელი',
    'apartments.twobed.feature7': 'ულტიმატური ზღვისა და ქალაქის ხედები',
    
    // Location Page
    'location.page.title': 'პრიმიუმ ლოკაცია სანაპიროზე',
    'location.page.subtitle': 'შესანიშნავად მოთავსებული ბათუმის გულში, რამდენიმე ნაბიჯით შავი ზღვისა და ძირითადი ღირსშესანიშნაობებიდან. გამოცადეთ სანაპირო ცხოვრების საუკეთესო შეუდარებელი მოხერხებულობით.',
    
    // Amenities
    'amenities.hero.title': 'მსოფლიო კლასის სერვისები',
    'amenities.hero.subtitle': 'ყველაფერი რაც გჭირდებათ დაუვიწყარი დასვენებისთვის',
    'amenities.premium.title': 'პრემიუმ ობიექტები',
    'amenities.premium.subtitle': 'ისიამოვნეთ ჩვენი ექსკლუზიური სერვისებით',
    'amenities.standard.title': 'ძირითადი სერვისები',
    'amenities.standard.subtitle': 'ყველა მოხერხებულობა რაც მოელით და მეტი',
    'amenities.pool.title': 'საცურაო აუზი და სპა',
    'amenities.pool.desc': 'დაისვენეთ ჩვენს განსაცვიფრებელ აუზში ზღვის პანორამული ხედებით',
    'amenities.fitness.title': 'ფიტნეს ცენტრი',
    'amenities.fitness.desc': 'თანამედროვე ვარჯიშის მოწყობილობები თქვენი ტრენინგისთვის',
    'amenities.spa.title': 'ველნესი და სპა',
    'amenities.spa.desc': 'განახლდით ჩვენი პროფესიონალური სპა პროცედურებით',
    'amenities.restaurant.title': 'პრემიუმ რესტორანი',
    'amenities.restaurant.desc': 'ისიამოვნეთ განსაკუთრებული კერძებით',
    'amenities.cafe.title': 'სანაპირო კაფე',
    'amenities.cafe.desc': 'დატკბით ყავითა და საჭმლით ოკეანის ხედებით',
    'amenities.bar.title': 'სახურავის ბარი',
    'amenities.bar.desc': 'დაისვენეთ პრემიუმ კოქტეილებით და მზის ჩასვლის ხედებით',
    'amenities.wifi.title': 'მაღალსიჩქარიანი WiFi',
    'amenities.wifi.desc': 'უფასო მაღალსიჩქარიანი ინტერნეტი მთელ ტერიტორიაზე',
    'amenities.security.title': '24/7 უსაფრთხოება',
    'amenities.security.desc': 'მუდმივი უსაფრთხოება და ზედამხედველობა',
    'amenities.reception.title': '24/7 რეცეფცია',
    'amenities.reception.desc': 'ჩვენი კონსიერჟის გუნდი ყოველთვის თქვენს სერვისშია',
    'amenities.parking.title': 'დაცული პარკინგი',
    'amenities.parking.desc': 'უფასო პარკინგი 24/7 უსაფრთხოებით',
    'amenities.ac.title': 'კლიმატკონტროლი',
    'amenities.ac.desc': 'ინდივიდუალური კონდიციონერი ყველა აპარტამენტში',
    'amenities.concierge.title': 'კონსიერჟ სერვისი',
    'amenities.concierge.desc': 'პერსონალიზებული დახმარება თქვენი ყველა საჭიროებისთვის',
    
    // Purchase Conditions
    'purchase.hero.title': 'შეძენისა და დაჯავშნის პირობები',
    'purchase.hero.subtitle': 'გამჭვირვალე პირობები თქვენი სიმშვიდისთვის',
    'purchase.breadcrumb': 'შეძენის პირობები',
    'purchase.payment.title': 'გადახდის პირობები',
    'purchase.payment.content': 'ჩვენ ვიღებთ საბანკო გადარიცხვებს, საკრედიტო/სადებეტო ბარათებს და ნაღდს. სრული გადახდა საჭიროა დაბინავებისას, თუ წინასწარ არ არის შეთანხმებული. ვთავაზობთ მოქნილ გადახდის გეგმებს გრძელვადიანი ყოფნისთვის.',
    'purchase.cancellation.title': 'გაუქმების პოლიტიკა',
    'purchase.cancellation.content': 'უფასო გაუქმება ჩამოსვლამდე 7 დღემდე. 7 დღეში გაუქმება იწვევს 50% საფასურს. გამოუცხადებლობა იწვევს სრულ საფასურს. ვაცნობიერებთ, რომ გეგმები იცვლება - დაგვიკავშირდით განსაკუთრებული შემთხვევებისთვის.',
    'purchase.deposit.title': 'უსაფრთხოების დეპოზიტი',
    'purchase.deposit.content': 'დაბინავებისას შეიძლება მოთხოვნილი იყოს უსაფრთხოების დეპოზიტი. თანხა განსხვავდება აპარტამენტის ტიპის მიხედვით. დეპოზიტები სრულად უბრუნდება შემოწმების შემდეგ, ჩვეულებრივ 3-5 სამუშაო დღის განმავლობაში.',
    'purchase.refund.title': 'თანხის დაბრუნების პოლიტიკა',
    'purchase.refund.content': 'თანხები უბრუნდება 14 სამუშაო დღის განმავლობაში თქვენს ორიგინალურ გადახდის მეთოდზე. დამუშავების საფასური არ უბრუნდება. უფასო პერიოდის შემდეგ გაუქმებისთვის ვრცელდება ნაწილობრივი დაბრუნება.',
    'purchase.important.title': 'მნიშვნელოვანი ინფორმაცია',
    'purchase.important.point1': 'დაბინავებისას საჭიროა მოქმედი პირადობის მოწმობა ან პასპორტი',
    'purchase.important.point2': 'მინიმალური ასაკი: 18 წელი',
    'purchase.important.point3': 'შინაური ცხოველები დაშვებულია წინასწარი თანხმობით (შესაძლოა დამატებითი საფასური)',
    'purchase.updated': 'ბოლო განახლება',
    'purchase.updateDate': 'იანვარი 2025',
    
    // Loyalty Program
    'loyalty.hero.title': 'Orbi ჯილდოების პროგრამა',
    'loyalty.hero.subtitle': 'დააგროვეთ ქულები ყოველი ყოფნით და მიიღეთ ექსკლუზიური სარგებელი',
    'loyalty.hero.cta': 'შემოგვიერთდი - უფასოა',
    'loyalty.howItWorks.title': 'როგორ მუშაობს',
    'loyalty.howItWorks.subtitle': 'დაიწყეთ ჯილდოების მოპოვება სამ მარტივ ნაბიჯად',
    'loyalty.step1.title': 'შექმენით ანგარიში',
    'loyalty.step1.desc': 'დარეგისტრირდით უფასოდ და დაიწყეთ მოპოვება დაუყოვნებლივ',
    'loyalty.step2.title': 'დააგროვეთ ქულები',
    'loyalty.step2.desc': 'მიიღეთ 10 ქულა ყოველი დახარჯული ლარისთვის',
    'loyalty.step3.title': 'გამოიყენეთ ჯილდოები',
    'loyalty.step3.desc': 'გამოიყენეთ თქვენი ქულები ფასდაკლებებისა და ექსკლუზიური პრივილეგიებისთვის',
    'loyalty.benefits.title': 'წევრის სარგებელი',
    'loyalty.benefits.subtitle': 'ექსკლუზიური უპირატესობები ჩვენი ღირებული წევრებისთვის',
    'loyalty.benefit1': 'ადრეული დაბინავება და გვიანი დატოვება ხელმისაწვდომობის შემთხვევაში',
    'loyalty.benefit2': 'უფასო ნომრის გაუმჯობესება (ხელმისაწვდომობის შემთხვევაში)',
    'loyalty.benefit3': 'პრიორიტეტული დაჯავშნა პიკურ სეზონზე',
    'loyalty.benefit4': 'ექსკლუზიური წევრებისთვის განკუთვნილი ტარიფები და აქციები',
    'loyalty.benefit5': 'დაბადების დღისა და იუბილეების მოულოდნელობები',
    'loyalty.testimonials.title': 'რას ამბობენ ჩვენი წევრები',
    'loyalty.testimonial1': 'ლოიალობის პროგრამა საოცარია! ბოლო დაჯავშნაზე დავზოგე 200 ლარზე მეტი და მივიღე უფასო ნომრის გაუმჯობესება!',
    'loyalty.testimonial2': 'წევრობა ბათუმში ჩემს რეგულარულ მოგზაურობებს გაცილებით უკეთესს ხდის. პრივილეგიები რეალურია!',
    'loyalty.cta.title': 'მზად ხართ დაწყებისთვის?',
    'loyalty.cta.subtitle': 'შემოუერთდით ათასობით კმაყოფილ წევრს დღეს',
    'loyalty.cta.button': 'შექმენით უფასო ანგარიში',
    
    // About Us
    'about.hero.title': 'Orbi City ბათუმის შესახებ',
    'about.hero.subtitle': 'თქვენი კარიბჭე დაუვიწყარი გამოცდილებებისკენ შავი ზღვის სანაპიროზე',
    'about.story.title': 'ჩვენი ისტორია',
    'about.story.p1': 'Orbi City ბათუმი წარმოადგენს თანამედროვე აპარტოტელის ცხოვრების მწვერვალს საქართველოს შავი ზღვის სანაპიროზე. დაარსებიდან, ჩვენ ვუძღვნით თავს სტუმრებისთვის ლუქსის, კომფორტისა და ავთენტური ქართული სტუმართმოყვარეობის უბადლო ნაზავის უზრუნველყოფას.',
    'about.story.p2': 'სტრატეგიულად მდებარე ბათუმის გულში, მხოლოდ 50 მეტრში სუფთა პლაჟიდან და ქალაქის მთავარ ღირსშესანიშნაობებთან ახლოს, ჩვენ ვთავაზობთ სრულყოფილ ბაზას როგორც დასვენებისთვის, ისე ბიზნეს მოგზაურებისთვის.',
    'about.story.p3': 'ჩვენი ერთგულება ხარისხს აისახება ყოველ დეტალში - ჩვენი საგულდაგულოდ დაპროექტებული აპარტამენტებიდან თვალწარმტაცი ზღვის ხედებით მსოფლიო კლასის სერვისებამდე და პერსონალიზებულ კონსიერჟ მომსახურებამდე.',
    'about.mission.title': 'ჩვენი მისია',
    'about.mission.desc': 'თითოეულ სტუმარს მივაწოდოთ არაჩვეულებრივი გამოცდილება, რომელიც აღემატება მოლოდინებს, აერთიანებს სახლის კომფორტს ხუთვარსკვლავიანი ლუქსით და ავთენტური ქართული სითბით.',
    'about.vision.title': 'ჩვენი ხედვა',
    'about.vision.desc': 'ვიყოთ აღიარებული, როგორც პრემიერ აპარტოტელის დანიშნულების ადგილი შავი ზღვის სანაპიროზე, ვაყენებთ სტანდარტს სტუმართმოყვარეობის შესანიშნაობისთვის და ვქმნით დაუვიწყარ მოგონებებს ჩვენი სტუმრებისთვის.',
    'about.values.title': 'ჩვენი ძირითადი ღირებულებები',
    'about.values.subtitle': 'პრინციპები, რომლებიც წარმართავს ყველაფერს რასაც ვაკეთებთ',
    'about.value1.title': 'სტუმრზე ორიენტირებული სრულყოფილება',
    'about.value1.desc': 'ყოველი გადაწყვეტილება, რომელსაც ვიღებთ, პირველ რიგში ითვალისწინებს ჩვენი სტუმრების კმაყოფილებას',
    'about.value2.title': 'ხარისხი კომპრომისის გარეშე',
    'about.value2.desc': 'ვინარჩუნებთ უმაღლეს სტანდარტებს ჩვენი მომსახურების ყველა ასპექტში',
    'about.value3.title': 'ინოვაცია და ზრდა',
    'about.value3.desc': 'მუდმივად ვითვითარდებით თანამედროვე მოგზაურების საჭიროებების დასაკმაყოფილებლად',
    'about.stat1': 'ლუქს აპარტამენტი',
    'about.stat2': 'ბედნიერი სტუმარი',
    'about.stat3': 'სტუმრის რეიტინგი',
    'about.stat4': 'მომსახურება',
    'about.gallery.title': 'გამოცადეთ Orbi City',
    
    // Apartment Detail
    'apartmentDetail.notFound': 'აპარტამენტი ვერ მოიძებნა',
    'apartmentDetail.backToList': 'უკან აპარტამენტებზე',
    'apartmentDetail.description': 'აღწერა',
    'apartmentDetail.booking': 'დაჯავშნა',
    'apartmentDetail.watchVideos': 'ვიდეოების ნახვა',
    
    // YouTube Videos
    'youtubeVideos.title': 'ვიდეო გალერეა',
    'youtubeVideos.subtitle': 'აღმოაჩინეთ Orbi City ბათუმი ჩვენი ვიდეოების მეშვეობით',
    'youtubeVideos.breadcrumb': 'ვიდეოები',
    'youtubeVideos.error': 'ვიდეოების ჩატვირთვა ამჟამად შეუძლებელია. გთხოვთ სცადოთ მოგვიანებით.',
    'youtubeVideos.noVideos': 'ვიდეოები მიუწვდომელია',
    'youtubeVideos.noDescription': 'უყურეთ ამ ვიდეოს მეტის გასაგებად',
    'youtubeVideos.watchNow': 'ყურება',
    'youtubeVideos.featured': 'რჩეული',
    'youtubeVideos.noVideosInCategory': 'ამ კატეგორიაში ჯერ არ არის ვიდეოები',
    'youtubeVideos.category.all': 'ყველა ვიდეო',
    'youtubeVideos.category.propertyTours': 'ობიექტის ტურები',
    'youtubeVideos.category.testimonials': 'მიმოხილვები',
    'youtubeVideos.category.areaGuide': 'გზამკვლევი',
    'youtubeVideos.category.amenities': 'სერვისები',
  },
  ru: {
    // Navigation
    'nav.home': 'Главная',
    'nav.rooms': 'Номера',
    'nav.amenities': 'Удобства',
    'nav.location': 'Расположение',
    'nav.reviews': 'Отзывы',
    'nav.contact': 'Контакты',
    'nav.bookNow': 'Забронировать',
    'nav.videos': 'Видео',
    'nav.apartments': 'Апартаменты',
    'nav.loyalty': 'Бонусы',
    'nav.about': 'О нас',
    
    // Index Videos Section
    'index.videos.title': 'Ознакомьтесь с нашими турами по объектам',
    'index.videos.subtitle': 'Смотрите наши последние видео, демонстрирующие красоту и роскошь Orbi City Батуми',
    'index.videos.viewAll': 'Смотреть все видео',
    
    // Hero
    'hero.title': 'Ваш идеальный приморский отдых',
    'hero.subtitle': 'Роскошные апартаменты с видом на море в сердце Батуми',
    'hero.bookNowPayLater': 'ЗАБРОНИРУЙТЕ СЕЙЧАС / ОПЛАТИТЕ ПОЗЖЕ',
    'hero.whatsapp': 'WhatsApp',
    
    // Booking Widget
    'booking.title': 'Проверить наличие',
    'booking.selectDate': 'Выберите дату',
    'booking.checkIn': 'Заезд',
    'booking.checkOut': 'Выезд',
    'booking.guests': 'Гости',
    'booking.checkAvailability': 'Проверить наличие',
    
    // Rooms
    'rooms.title': 'Найдите ваше идеальное пространство',
    'rooms.subtitle': 'Каждый апартамент тщательно спроектирован для создания уникального опыта',
    'rooms.suite': 'Люкс с видом на море',
    'rooms.suiteDesc': 'Элегантный люкс с захватывающими видами на море, идеальный для пар или индивидуальных путешественников',
    'rooms.deluxe': 'Делюкс люкс с видом на море',
    'rooms.deluxeDesc': 'Более просторный и роскошный люкс с улучшенными удобствами и первоклассным видом на море',
    'rooms.superior': 'Супериор люкс с видом на море',
    'rooms.superiorDesc': 'Премиум люкс с отдельной жилой зоной и лучшими панорамными видами на море',
    'rooms.family': 'Супериор семейный люкс',
    'rooms.familyDesc': 'Просторный люкс с несколькими комнатами, идеальный для семей или групп',
    'rooms.twobed': 'Двухкомнатный панорамный люкс',
    'rooms.twobedDesc': 'Вершина роскоши. Просторный люкс с двумя спальнями и потрясающей панорамной террасой',
    'rooms.viewDetails': 'Подробнее',
    'rooms.bookNow': 'Забронировать',
    'rooms.from': 'От',
    'rooms.night': '/ночь',
    'rooms.size': 'Площадь',
    'rooms.guests': 'Гостей',
    'rooms.watchVideo': 'Смотреть тур по объекту',
    
    // Amenities
    'amenities.title': 'Удобства мирового класса',
    'amenities.subtitle': 'Всё, что нужно для идеального отдыха',
    'amenities.seaView': 'Вид на море',
    'amenities.fountains': 'Рядом с фонтанами',
    'amenities.kitchen': 'Полноценная кухня',
    'amenities.reception': 'Ресепшн 24/7',
    'amenities.pool': 'Бассейн',
    'amenities.parking': 'Парковка',
    'amenities.wifi': 'Высокоскоростной WiFi',
    'amenities.ac': 'Кондиционер',
    'amenities.housekeeping': 'Уборка номеров',
    'amenities.security': 'Охрана 24/7',
    'amenities.concierge': 'Консьерж-сервис',
    'amenities.restaurant': 'Ресторан',
    
    // Location
    'location.title': 'Премиальное расположение в Батуми',
    'location.subtitle': 'В нескольких шагах от Чёрного моря и главных достопримечательностей',
    'location.beach': 'Пляж Чёрного моря',
    'location.beachDist': '50 метров',
    'location.fountains': 'Поющие фонтаны',
    'location.fountainsDist': '100 метров',
    'location.airport': 'Аэропорт Батуми',
    'location.airportDist': '5 километров',
    
    // Reviews
    'reviews.title': 'Отзывы гостей',
    'reviews.subtitle': 'Что говорят о нас наши гости',
    'reviews.rating': 'Рейтинг гостей',
    'reviews.review1': 'Потрясающие виды на Чёрное море! Апартаменты были роскошными, а персонал невероятно гостеприимным.',
    'reviews.review2': 'Идеальное расположение рядом с пляжем и фонтанами. Апартаменты были безупречно чистыми и хорошо оборудованными.',
    'reviews.review3': 'Удивительный опыт! Вид на море с нашего балкона был захватывающим. Очень рекомендую!',
    
    // CTA
    'cta.title': 'Готовы испытать роскошь у моря?',
    'cta.subtitle': 'Забронируйте ваши идеальные апартаменты сегодня',
    'cta.button': 'Забронировать проживание',
    
    // Footer
    'footer.description': 'Роскошные апартаменты с обслуживанием в сердце Батуми, Грузия. В нескольких шагах от Чёрного моря.',
    'footer.quickLinks': 'Быстрые ссылки',
    'footer.contact': 'Свяжитесь с нами',
    'footer.phone': 'Телефон',
    'footer.email': 'Email',
    'footer.address': 'Адрес',
    'footer.followUs': 'Подписывайтесь',
    'footer.rights': '© 2025 Orbi City Батуми. Все права защищены.',
    
    // Apartments Page
    'apartments.hero.title': 'Роскошные апартаменты в Батуми',
    'apartments.hero.subtitle': 'Откройте для себя изысканную коллекцию апартаментов с видом на море, каждый из которых создан для обеспечения максимального комфорта и изысканности. От уютных люксов до просторных семейных апартаментов.',
    'apartments.section.title': 'Найдите ваше идеальное пространство',
    'apartments.section.subtitle': 'Каждый апартамент тщательно спроектирован для создания непревзойдённого опыта. Изучите наши предложения и найдите то, что подходит именно вам.',
    'apartments.sqm': 'м²',
    'apartments.guests': 'Гостей',
    'apartments.bed': 'Кровать',
    'apartments.beds': 'Кроватей',
    'apartments.sofaBed': 'Диван-кровать',
    'apartments.bath': 'Ванная',
    'apartments.baths': 'Ванных',
    'apartments.bidet': 'Биде',
    'apartments.keyFeatures': 'Ключевые особенности',
    'apartments.bookNow': 'Забронировать / Оплатить позже',
    'apartments.checkAvailability': 'Проверить наличие',
    
    // Suite
    'apartments.suite.title': 'Люкс с видом на море',
    'apartments.suite.desc': 'Элегантный люкс с захватывающими панорамными видами на Чёрное море. Идеально подходит для пар или индивидуальных путешественников, ищущих спокойный отдых с современными удобствами и изысканным дизайном. Просыпайтесь под потрясающие восходы над морем с вашего личного балкона.',
    'apartments.suite.feature1': 'Личный балкон с видом на море',
    'apartments.suite.feature2': 'Полностью оборудованная мини-кухня',
    'apartments.suite.feature3': 'Высокоскоростной WiFi',
    'apartments.suite.feature4': 'Умный климат-контроль',
    'apartments.suite.feature5': '55" Smart TV со стримингом',
    'apartments.suite.feature6': 'Кровать King Size с премиум постельным бельём',
    
    // Deluxe
    'apartments.deluxe.title': 'Делюкс люкс с видом на море',
    'apartments.deluxe.desc': 'Более просторный и роскошный люкс с улучшенными удобствами и первоклассными видами на море. Создан для взыскательных гостей, которые ценят внимание к деталям и комфорт. Отдельная гостиная зона предоставляет дополнительное пространство для отдыха и развлечений.',
    'apartments.deluxe.feature1': 'Просторный балкон с видом на море',
    'apartments.deluxe.feature2': 'Отдельная гостиная и обеденная зона',
    'apartments.deluxe.feature3': 'Полноценная кухня с премиум техникой',
    'apartments.deluxe.feature4': 'Бесплатный высокоскоростной WiFi',
    'apartments.deluxe.feature5': 'Двухзонный климат-контроль',
    'apartments.deluxe.feature6': 'Премиум развлекательная система',
    
    // Superior
    'apartments.superior.title': 'Супериор люкс с видом на море',
    'apartments.superior.desc': 'Наш премиум люкс с отдельной спальней, роскошной жилой зоной и лучшими панорамными видами на Чёрное море. Идеально подходит для гостей, желающих дополнительного пространства и премиум удобств. Угловое расположение обеспечивает максимальное естественное освещение и потрясающие виды на океан.',
    'apartments.superior.feature1': 'Угловые панорамные виды на море',
    'apartments.superior.feature2': 'Одна отдельная спальня',
    'apartments.superior.feature3': 'Просторная обеденная зона',
    'apartments.superior.feature4': 'Современная полноценная ванная',
    'apartments.superior.feature5': 'Дизайнерская мини-кухня',
    'apartments.superior.feature6': 'Люксовые принадлежности для ванной',
    'apartments.superior.feature7': 'Кровать King с потолочными зеркалами',
    
    // Family
    'apartments.family.title': 'Супериор семейный люкс с видом на море',
    'apartments.family.desc': 'Просторный люкс с двумя спальнями и двумя ванными комнатами, идеально подходит для семей или групп до 6 гостей. Наслаждайтесь комфортом и приватностью с отдельными спальными зонами, сохраняя связь в просторной гостиной. Идеально для создания незабываемых воспоминаний с близкими.',
    'apartments.family.feature1': 'Просторный личный балкон',
    'apartments.family.feature2': 'Две отдельные спальни',
    'apartments.family.feature3': 'Две полноценные ванные с биде',
    'apartments.family.feature4': 'Полноценная кухня и обеденная зона',
    'apartments.family.feature5': 'Стиральная машина в номере',
    'apartments.family.feature6': 'Приоритетные услуги консьержа',
    'apartments.family.feature7': 'Кровати King с премиум функциями',
    
    // Two Bedroom
    'apartments.twobed.title': 'Двухкомнатный панорамный люкс',
    'apartments.twobed.desc': 'Вершина роскошной жизни в Батуми. Этот просторный люкс включает две главные спальни и впечатляющую 270° панорамную террасу с непрерывными видами на Чёрное море. Идеально подходит для семей или групп, ищущих максимум пространства, комфорта и захватывающих пейзажей.',
    'apartments.twobed.feature1': '270° панорамная терраса с видом на океан',
    'apartments.twobed.feature2': '2 главные спальни с собственными ванными',
    'apartments.twobed.feature3': '2 раскладных дивана-кровати',
    'apartments.twobed.feature4': '2 кровати King с потолочными зеркалами',
    'apartments.twobed.feature5': 'Гурманская кухня',
    'apartments.twobed.feature6': 'Дизайнерская люксовая мебель',
    'apartments.twobed.feature7': 'Непревзойдённые виды на море и город',
    
    // Location Page
    'location.page.title': 'Премиальное расположение на берегу моря',
    'location.page.subtitle': 'Идеально расположенный в сердце Батуми, в нескольких шагах от Чёрного моря и главных достопримечательностей. Испытайте лучшее от прибрежной жизни с непревзойдённым удобством.',
    
    // Amenities
    'amenities.hero.title': 'Удобства мирового класса',
    'amenities.hero.subtitle': 'Всё, что нужно для незабываемого отдыха',
    'amenities.premium.title': 'Премиальные объекты',
    'amenities.premium.subtitle': 'Наслаждайтесь нашими эксклюзивными удобствами, созданными для вашего максимального комфорта',
    'amenities.standard.title': 'Основные услуги',
    'amenities.standard.subtitle': 'Все удобства, которые вы ожидаете, и даже больше',
    'amenities.pool.title': 'Бассейн и спа',
    'amenities.pool.desc': 'Расслабьтесь в нашем потрясающем бассейне с панорамными видами на море',
    'amenities.fitness.title': 'Фитнес-центр',
    'amenities.fitness.desc': 'Современное спортивное оборудование для вашей тренировки',
    'amenities.spa.title': 'Велнес и спа',
    'amenities.spa.desc': 'Восстановите силы с нашими профессиональными спа-процедурами',
    'amenities.restaurant.title': 'Изысканный ресторан',
    'amenities.restaurant.desc': 'Наслаждайтесь изысканной кухней от шеф-поваров мирового класса',
    'amenities.cafe.title': 'Кафе на берегу моря',
    'amenities.cafe.desc': 'Наслаждайтесь кофе и лёгкими закусками с потрясающими видами на океан',
    'amenities.bar.title': 'Бар на крыше',
    'amenities.bar.desc': 'Расслабьтесь с премиальными коктейлями и захватывающими видами заката',
    'amenities.wifi.title': 'Высокоскоростной WiFi',
    'amenities.wifi.desc': 'Бесплатный высокоскоростной интернет на всей территории',
    'amenities.security.title': 'Охрана 24/7',
    'amenities.security.desc': 'Круглосуточная охрана и видеонаблюдение для вашего спокойствия',
    'amenities.reception.title': 'Ресепшн 24/7',
    'amenities.reception.desc': 'Наша команда консьержей всегда к вашим услугам',
    'amenities.parking.title': 'Охраняемая парковка',
    'amenities.parking.desc': 'Бесплатная парковка с круглосуточной охраной',
    'amenities.ac.title': 'Климат-контроль',
    'amenities.ac.desc': 'Индивидуальный кондиционер в каждом апартаменте',
    'amenities.concierge.title': 'Консьерж-сервис',
    'amenities.concierge.desc': 'Персонализированная помощь для всех ваших потребностей',
    
    // Purchase Conditions
    'purchase.hero.title': 'Условия покупки и бронирования',
    'purchase.hero.subtitle': 'Чёткие, прозрачные условия для вашего спокойствия',
    'purchase.breadcrumb': 'Условия покупки',
    'purchase.payment.title': 'Условия оплаты',
    'purchase.payment.content': 'Мы принимаем банковские переводы, кредитные/дебетовые карты и наличные. Полная оплата требуется при заселении, если не согласовано заранее. Мы предлагаем гибкие планы оплаты для длительного проживания. Принимаются все основные кредитные карты.',
    'purchase.cancellation.title': 'Политика отмены',
    'purchase.cancellation.content': 'Бесплатная отмена за 7 дней до прибытия. Отмены в течение 7 дней влекут 50% комиссию. Неявка приводит к полной оплате. Мы понимаем, что планы меняются - свяжитесь с нами для особых обстоятельств.',
    'purchase.deposit.title': 'Страховой депозит',
    'purchase.deposit.content': 'При заселении может потребоваться возвратный страховой депозит. Сумма зависит от типа апартаментов. Депозиты полностью возвращаются после проверки, обычно в течение 3-5 рабочих дней.',
    'purchase.refund.title': 'Политика возврата',
    'purchase.refund.content': 'Возвраты обрабатываются в течение 14 рабочих дней на ваш исходный способ оплаты. Комиссия за обработку не возвращается. Для отмен за пределами бесплатного периода применяется частичный возврат согласно нашей политике отмены.',
    'purchase.important.title': 'Важная информация',
    'purchase.important.point1': 'При заселении требуется действующее удостоверение личности или паспорт',
    'purchase.important.point2': 'Минимальный возраст: 18 лет',
    'purchase.important.point3': 'Домашние животные разрешены с предварительного согласия (может взиматься дополнительная плата)',
    'purchase.updated': 'Последнее обновление',
    'purchase.updateDate': 'Январь 2025',
    
    // Loyalty Program
    'loyalty.hero.title': 'Программа вознаграждений Orbi',
    'loyalty.hero.subtitle': 'Зарабатывайте баллы с каждым проживанием и получайте эксклюзивные преимущества',
    'loyalty.hero.cta': 'Присоединяйтесь - это бесплатно',
    'loyalty.howItWorks.title': 'Как это работает',
    'loyalty.howItWorks.subtitle': 'Начните зарабатывать награды за три простых шага',
    'loyalty.step1.title': 'Создайте аккаунт',
    'loyalty.step1.desc': 'Зарегистрируйтесь бесплатно и начните зарабатывать сразу',
    'loyalty.step2.title': 'Зарабатывайте баллы',
    'loyalty.step2.desc': 'Получайте 10 баллов за каждый потраченный лари',
    'loyalty.step3.title': 'Используйте награды',
    'loyalty.step3.desc': 'Используйте ваши баллы для скидок и эксклюзивных привилегий',
    'loyalty.benefits.title': 'Преимущества членства',
    'loyalty.benefits.subtitle': 'Эксклюзивные преимущества для наших ценных участников',
    'loyalty.benefit1': 'Ранний заезд и поздний выезд при наличии возможности',
    'loyalty.benefit2': 'Бесплатное повышение категории номера (при наличии возможности)',
    'loyalty.benefit3': 'Приоритетное бронирование в высокий сезон',
    'loyalty.benefit4': 'Эксклюзивные тарифы и акции только для членов',
    'loyalty.benefit5': 'Сюрпризы на день рождения и юбилей',
    'loyalty.testimonials.title': 'Что говорят наши участники',
    'loyalty.testimonial1': 'Программа лояльности потрясающая! При последнем бронировании я сэкономил более 200 лари и получил бесплатное повышение номера!',
    'loyalty.testimonial2': 'Членство сделало мои регулярные поездки в Батуми намного лучше. Привилегии реальные!',
    'loyalty.cta.title': 'Готовы начать зарабатывать?',
    'loyalty.cta.subtitle': 'Присоединяйтесь к тысячам довольных участников сегодня',
    'loyalty.cta.button': 'Создать бесплатный аккаунт',
    
    // About Us
    'about.hero.title': 'Об Orbi City Батуми',
    'about.hero.subtitle': 'Ваши врата к незабываемым впечатлениям на побережье Чёрного моря',
    'about.story.title': 'Наша история',
    'about.story.p1': 'Orbi City Батуми представляет вершину современной жизни апартотеля на потрясающем черноморском побережье Грузии. С момента основания мы посвятили себя предоставлению гостям непревзойдённого сочетания роскоши, комфорта и аутентичного грузинского гостеприимства.',
    'about.story.p2': 'Стратегически расположенный в сердце Батуми, всего в 50 метрах от чистого пляжа и в пешей доступности от главных достопримечательностей города, мы предлагаем идеальную базу как для отдыха, так и для деловых путешественников.',
    'about.story.p3': 'Наша приверженность совершенству отражается в каждой детали - от наших тщательно спроектированных апартаментов с захватывающими видами на море до удобств мирового класса и персонализированных консьерж-услуг.',
    'about.mission.title': 'Наша миссия',
    'about.mission.desc': 'Предоставить каждому гостю исключительный опыт, превосходящий ожидания, сочетающий домашний комфорт с пятизвёздочной роскошью и аутентичным грузинским теплом.',
    'about.vision.title': 'Наше видение',
    'about.vision.desc': 'Быть признанным как ведущий апартотель на побережье Чёрного моря, устанавливающий стандарты гостеприимства и создающий незабываемые воспоминания для наших гостей.',
    'about.values.title': 'Наши основные ценности',
    'about.values.subtitle': 'Принципы, которые направляют всё, что мы делаем',
    'about.value1.title': 'Ориентация на гостя',
    'about.value1.desc': 'Каждое наше решение ставит удовлетворение и комфорт гостей на первое место',
    'about.value2.title': 'Качество без компромиссов',
    'about.value2.desc': 'Мы поддерживаем высочайшие стандарты во всех аспектах нашего сервиса',
    'about.value3.title': 'Инновации и развитие',
    'about.value3.desc': 'Постоянно развиваемся для удовлетворения потребностей современных путешественников',
    'about.stat1': 'Люксовых апартаментов',
    'about.stat2': 'Довольных гостей',
    'about.stat3': 'Рейтинг гостей',
    'about.stat4': 'Сервис',
    'about.gallery.title': 'Испытайте Orbi City',
    
    // Apartment Detail
    'apartmentDetail.notFound': 'Апартамент не найден',
    'apartmentDetail.backToList': 'Назад к апартаментам',
    'apartmentDetail.description': 'Описание',
    'apartmentDetail.booking': 'Бронирование',
    'apartmentDetail.watchVideos': 'Смотреть видео',
    
    // YouTube Videos
    'youtubeVideos.title': 'Видеогалерея',
    'youtubeVideos.subtitle': 'Откройте для себя Orbi City Батуми через наши видео',
    'youtubeVideos.breadcrumb': 'Видео',
    'youtubeVideos.error': 'Не удаётся загрузить видео в данный момент. Пожалуйста, попробуйте позже.',
    'youtubeVideos.noVideos': 'Видео недоступны',
    'youtubeVideos.noDescription': 'Посмотрите это видео, чтобы узнать больше',
    'youtubeVideos.watchNow': 'Смотреть',
    'youtubeVideos.featured': 'Рекомендуемое',
    'youtubeVideos.noVideosInCategory': 'В этой категории пока нет видео',
    'youtubeVideos.category.all': 'Все видео',
    'youtubeVideos.category.propertyTours': 'Туры по объектам',
    'youtubeVideos.category.testimonials': 'Отзывы',
    'youtubeVideos.category.areaGuide': 'Путеводитель',
    'youtubeVideos.category.amenities': 'Удобства',
  },
  tr: {
    // Navigation
    'nav.home': 'Ana Sayfa',
    'nav.rooms': 'Odalar',
    'nav.amenities': 'Olanaklar',
    'nav.location': 'Konum',
    'nav.reviews': 'Yorumlar',
    'nav.contact': 'İletişim',
    'nav.bookNow': 'Rezervasyon Yap',
    'nav.videos': 'Videolar',
    'nav.apartments': 'Apartmanlar',
    'nav.loyalty': 'Bonuslar',
    'nav.about': 'Hakkımızda',
    
    // Index Videos Section
    'index.videos.title': 'Tesis Turlarımızı Keşfedin',
    'index.videos.subtitle': 'Orbi City Batum\'un güzelliğini ve lüksünü sergileyen en son videolarımızı izleyin',
    'index.videos.viewAll': 'Tüm Videoları Gör',
    
    // Hero
    'hero.title': 'Mükemmel Sahil Kaçışınız',
    'hero.subtitle': 'Batum\'un Kalbinde Deniz Manzaralı Lüks Apartmanlar',
    'hero.bookNowPayLater': 'HEMEN REZERVE EDİN / SONRA ÖDEYİN',
    'hero.whatsapp': 'WhatsApp',
    
    // Booking Widget
    'booking.title': 'Müsaitliği Kontrol Et',
    'booking.selectDate': 'Tarih seçin',
    'booking.checkIn': 'Giriş',
    'booking.checkOut': 'Çıkış',
    'booking.guests': 'Misafirler',
    'booking.checkAvailability': 'Müsaitliği Kontrol Et',
    
    // Rooms
    'rooms.title': 'Mükemmel Alanınızı Bulun',
    'rooms.subtitle': 'Her apartman eşsiz bir deneyim sunmak için özenle tasarlanmıştır',
    'rooms.suite': 'Deniz Manzaralı Süit',
    'rooms.suiteDesc': 'Çiftler veya bireysel gezginler için ideal, nefes kesici deniz manzaralı zarif süit',
    'rooms.deluxe': 'Deniz Manzaralı Deluxe Süit',
    'rooms.deluxeDesc': 'Geliştirilmiş olanaklarla daha geniş ve lüks süit, birinci sınıf deniz manzarası',
    'rooms.superior': 'Deniz Manzaralı Superior Süit',
    'rooms.superiorDesc': 'Ayrı oturma alanı ve en iyi panoramik deniz manzaralı premium süit',
    'rooms.family': 'Superior Aile Süiti',
    'rooms.familyDesc': 'Aileler veya gruplar için ideal, birden fazla odalı geniş süit',
    'rooms.twobed': 'İki Yatak Odalı Panoramik Süit',
    'rooms.twobedDesc': 'Lüksün zirvesi. İki yatak odası ve muhteşem panoramik teraslı geniş süit',
    'rooms.viewDetails': 'Detayları Gör',
    'rooms.bookNow': 'Rezervasyon Yap',
    'rooms.from': 'den itibaren',
    'rooms.night': '/gece',
    'rooms.size': 'Boyut',
    'rooms.guests': 'Misafir',
    'rooms.watchVideo': 'Tesis Turunu İzle',
    
    // Amenities
    'amenities.title': 'Dünya Standartlarında Olanaklar',
    'amenities.subtitle': 'Mükemmel bir konaklama için ihtiyacınız olan her şey',
    'amenities.seaView': 'Deniz Manzarası',
    'amenities.fountains': 'Fıskiyelere Yakın',
    'amenities.kitchen': 'Tam Donanımlı Mutfak',
    'amenities.reception': '7/24 Resepsiyon',
    'amenities.pool': 'Yüzme Havuzu',
    'amenities.parking': 'Otopark',
    'amenities.wifi': 'Yüksek Hızlı WiFi',
    'amenities.ac': 'Klima',
    'amenities.housekeeping': 'Kat Hizmeti',
    'amenities.security': '7/24 Güvenlik',
    'amenities.concierge': 'Concierge Hizmeti',
    'amenities.restaurant': 'Restoran',
    
    // Location
    'location.title': 'Batum\'da Premium Konum',
    'location.subtitle': 'Karadeniz ve önemli turistik yerlere adım mesafesinde',
    'location.beach': 'Karadeniz Plajı',
    'location.beachDist': '50 metre',
    'location.fountains': 'Dans Eden Fıskiyeler',
    'location.fountainsDist': '100 metre',
    'location.airport': 'Batum Havalimanı',
    'location.airportDist': '5 kilometre',
    
    // Reviews
    'reviews.title': 'Misafir Yorumları',
    'reviews.subtitle': 'Misafirlerimiz hakkımızda ne diyor',
    'reviews.rating': 'Misafir Puanı',
    'reviews.review1': 'Karadeniz\'in kesinlikle muhteşem manzaraları! Apartman lükstü ve personel inanılmaz derecede konukseverdı.',
    'reviews.review2': 'Plaja ve fıskiyelere yakın mükemmel konum. Apartman tertemiz ve iyi donanımlıydı.',
    'reviews.review3': 'Harika bir deneyim! Balkonumuzdan deniz manzarası nefes kesiciydi. Kesinlikle tavsiye ederim!',
    
    // CTA
    'cta.title': 'Deniz Kenarında Lüks Yaşamaya Hazır mısınız?',
    'cta.subtitle': 'Mükemmel apartmanınızı bugün rezerve edin',
    'cta.button': 'Konaklamanızı Rezerve Edin',
    
    // Footer
    'footer.description': 'Gürcistan, Batum\'un kalbinde hizmetli lüks apartmanlar. Karadeniz\'e adım mesafesinde.',
    'footer.quickLinks': 'Hızlı Bağlantılar',
    'footer.contact': 'Bize Ulaşın',
    'footer.phone': 'Telefon',
    'footer.email': 'E-posta',
    'footer.address': 'Adres',
    'footer.followUs': 'Bizi Takip Edin',
    'footer.rights': '© 2025 Orbi City Batum. Tüm hakları saklıdır.',
    
    // Apartments Page
    'apartments.hero.title': 'Batum\'da Lüks Apartmanlar',
    'apartments.hero.subtitle': 'Her biri nihai konfor ve zarafet sağlamak için tasarlanmış, deniz manzaralı seçkin apartman koleksiyonumuzu keşfedin. Özel süitlerden geniş aile konaklama yerlerine.',
    'apartments.section.title': 'Mükemmel Alanınızı Bulun',
    'apartments.section.subtitle': 'Her apartman eşsiz bir deneyim sunmak için özenle tasarlanmıştır. Tekliflerimizi keşfedin ve size uygun olanı bulun.',
    'apartments.sqm': 'm²',
    'apartments.guests': 'Misafir',
    'apartments.bed': 'Yatak',
    'apartments.beds': 'Yatak',
    'apartments.sofaBed': 'Çekyat',
    'apartments.bath': 'Banyo',
    'apartments.baths': 'Banyo',
    'apartments.bidet': 'Bide',
    'apartments.keyFeatures': 'Temel Özellikler',
    'apartments.bookNow': 'Rezerve Et / Sonra Öde',
    'apartments.checkAvailability': 'Müsaitliği Kontrol Et',
    
    // Suite
    'apartments.suite.title': 'Deniz Manzaralı Süit',
    'apartments.suite.desc': 'Karadeniz\'in nefes kesici panoramik manzaralarını sunan zarif süit. Modern olanaklar ve sofistike tasarımla sakin bir kaçış arayan çiftler veya bireysel gezginler için ideal. Özel balkonunuzdan deniz üzerindeki muhteşem gündoğumlarıyla uyanın.',
    'apartments.suite.feature1': 'Deniz Manzaralı Özel Balkon',
    'apartments.suite.feature2': 'Tam Donanımlı Mini Mutfak',
    'apartments.suite.feature3': 'Yüksek Hızlı WiFi',
    'apartments.suite.feature4': 'Akıllı Klima Kontrolü',
    'apartments.suite.feature5': 'Yayın Özellikli 55" Akıllı TV',
    'apartments.suite.feature6': 'Premium Çarşaflı King Size Yatak',
    
    // Deluxe
    'apartments.deluxe.title': 'Deniz Manzaralı Deluxe Süit',
    'apartments.deluxe.desc': 'Geliştirilmiş olanaklar ve birinci sınıf deniz manzaralı daha geniş ve lüks süit. Detaylara ve konfora önem veren seçici misafirler için tasarlandı. Ayrı oturma alanı dinlenme ve eğlence için ek alan sağlar.',
    'apartments.deluxe.feature1': 'Geniş Deniz Manzaralı Balkon',
    'apartments.deluxe.feature2': 'Ayrı Oturma ve Yemek Alanı',
    'apartments.deluxe.feature3': 'Premium Cihazlarla Tam Mutfak',
    'apartments.deluxe.feature4': 'Ücretsiz Yüksek Hızlı WiFi',
    'apartments.deluxe.feature5': 'Çift Bölgeli Klima Kontrolü',
    'apartments.deluxe.feature6': 'Premium Eğlence Sistemi',
    
    // Superior
    'apartments.superior.title': 'Deniz Manzaralı Superior Süit',
    'apartments.superior.desc': 'Ayrı yatak odası, lüks oturma alanı ve Karadeniz\'in en iyi panoramik manzaralarına sahip premium süitimiz. Ekstra alan ve premium olanaklar isteyen misafirler için ideal. Köşe konumu maksimum doğal ışık ve geniş okyanus manzarası sağlar.',
    'apartments.superior.feature1': 'Köşe Panoramik Deniz Manzaraları',
    'apartments.superior.feature2': 'Bir Ayrı Yatak Odası',
    'apartments.superior.feature3': 'Geniş Yemek Alanı',
    'apartments.superior.feature4': 'Modern Tam Banyo',
    'apartments.superior.feature5': 'Tasarımcı Mini Mutfak',
    'apartments.superior.feature6': 'Lüks Banyo Ürünleri',
    'apartments.superior.feature7': 'Tavan Aynalı King Yatak',
    
    // Family
    'apartments.family.title': 'Deniz Manzaralı Superior Aile Süiti',
    'apartments.family.desc': 'Aileler veya 6 misafire kadar gruplar için ideal, iki yatak odası ve iki banyolu geniş süit. Ayrı uyku alanlarıyla konfor ve mahremiyet keyfini çıkarırken geniş oturma alanında bağlantıyı koruyun. Sevdiklerinizle kalıcı anılar oluşturmak için ideal.',
    'apartments.family.feature1': 'Geniş Özel Balkon',
    'apartments.family.feature2': 'İki Ayrı Yatak Odası',
    'apartments.family.feature3': 'Bideli İki Tam Banyo',
    'apartments.family.feature4': 'Tam Mutfak ve Yemek Alanı',
    'apartments.family.feature5': 'Ünitede Çamaşır Makinesi',
    'apartments.family.feature6': 'Öncelikli Concierge Hizmetleri',
    'apartments.family.feature7': 'Premium Özellikli King Yataklar',
    
    // Two Bedroom
    'apartments.twobed.title': 'İki Yatak Odalı Panoramik Süit',
    'apartments.twobed.desc': 'Batum\'da lüks yaşamın zirvesi. Bu geniş süit, iki ana yatak odası ve Karadeniz\'in kesintisiz manzaralarını sunan muhteşem 270° panoramik teras içerir. Alan, konfor ve nefes kesici manzarada en iyisini arayan aileler veya gruplar için ideal.',
    'apartments.twobed.feature1': '270° Panoramik Okyanus Terası',
    'apartments.twobed.feature2': 'Ayrı Banyolu 2 Ana Yatak Odası',
    'apartments.twobed.feature3': '2 Dönüştürülebilir Çekyat',
    'apartments.twobed.feature4': 'Tavan Aynalı 2 King Yatak',
    'apartments.twobed.feature5': 'Gurme Mutfak',
    'apartments.twobed.feature6': 'Tasarımcı Lüks Mobilya',
    'apartments.twobed.feature7': 'Eşsiz Deniz ve Şehir Manzaraları',
    
    // Location Page
    'location.page.title': 'Sahil Kenarında Premium Konum',
    'location.page.subtitle': 'Batum\'un kalbinde mükemmel konumlandırılmış, Karadeniz ve önemli turistik yerlere adım mesafesinde. Eşsiz kolaylıkla kıyı yaşamının en iyisini deneyimleyin.',
    
    // Amenities
    'amenities.hero.title': 'Dünya Standartlarında Olanaklar',
    'amenities.hero.subtitle': 'Unutulmaz bir konaklama için ihtiyacınız olan her şey',
    'amenities.premium.title': 'Premium Tesisler',
    'amenities.premium.subtitle': 'Nihai konforunuz için tasarlanmış özel olanaklarımızın tadını çıkarın',
    'amenities.standard.title': 'Temel Hizmetler',
    'amenities.standard.subtitle': 'Beklediğiniz tüm kolaylıklar ve daha fazlası',
    'amenities.pool.title': 'Yüzme Havuzu ve Spa',
    'amenities.pool.desc': 'Panoramik deniz manzaralı muhteşem havuzumuzda rahatlayın',
    'amenities.fitness.title': 'Fitness Merkezi',
    'amenities.fitness.desc': 'Antrenman rutininiz için son teknoloji spor ekipmanları',
    'amenities.spa.title': 'Wellness ve Spa',
    'amenities.spa.desc': 'Profesyonel spa tedavilerimizle yenilenin',
    'amenities.restaurant.title': 'İnce Yemek Restoranı',
    'amenities.restaurant.desc': 'Dünya standartlarında şefler tarafından hazırlanan seçkin mutfağın tadını çıkarın',
    'amenities.cafe.title': 'Sahil Kafesi',
    'amenities.cafe.desc': 'Muhteşem okyanus manzarasıyla kahve ve hafif atıştırmalıkların tadını çıkarın',
    'amenities.bar.title': 'Çatı Barı',
    'amenities.bar.desc': 'Premium kokteyller ve nefes kesici gün batımı manzaralarıyla rahatlayın',
    'amenities.wifi.title': 'Yüksek Hızlı WiFi',
    'amenities.wifi.desc': 'Tüm tesiste ücretsiz yüksek hızlı internet',
    'amenities.security.title': '7/24 Güvenlik',
    'amenities.security.desc': 'Huzurunuz için 24 saat güvenlik ve gözetim',
    'amenities.reception.title': '7/24 Resepsiyon',
    'amenities.reception.desc': 'Concierge ekibimiz her zaman hizmetinizde',
    'amenities.parking.title': 'Güvenli Otopark',
    'amenities.parking.desc': '7/24 güvenlikli ücretsiz otopark',
    'amenities.ac.title': 'Klima Kontrolü',
    'amenities.ac.desc': 'Her apartmanda bireysel klima',
    'amenities.concierge.title': 'Concierge Hizmetleri',
    'amenities.concierge.desc': 'Tüm ihtiyaçlarınız için kişiselleştirilmiş yardım',
    
    // Purchase Conditions
    'purchase.hero.title': 'Satın Alma ve Rezervasyon Koşulları',
    'purchase.hero.subtitle': 'Huzurunuz için açık, şeffaf koşullar',
    'purchase.breadcrumb': 'Satın Alma Koşulları',
    'purchase.payment.title': 'Ödeme Koşulları',
    'purchase.payment.content': 'Banka havalesi, kredi/banka kartı ve nakit kabul ediyoruz. Önceden düzenlenmediği sürece check-in sırasında tam ödeme gereklidir. Uzun süreli konaklamalar için esnek ödeme planları sunuyoruz. Tüm büyük kredi kartları kabul edilir.',
    'purchase.cancellation.title': 'İptal Politikası',
    'purchase.cancellation.content': 'Varıştan 7 gün öncesine kadar ücretsiz iptal. 7 gün içindeki iptaller %50 ücret içerir. Gelmeme durumunda tam ücret alınır. Planların değiştiğini anlıyoruz - özel durumlar için bizimle iletişime geçin.',
    'purchase.deposit.title': 'Güvenlik Depozitosu',
    'purchase.deposit.content': 'Check-in sırasında iade edilebilir güvenlik depozitosu istenebilir. Miktar apartman tipine göre değişir. Depozitolar kontrolden sonra, genellikle 3-5 iş günü içinde tamamen iade edilir.',
    'purchase.refund.title': 'İade Politikası',
    'purchase.refund.content': 'İadeler 14 iş günü içinde orijinal ödeme yönteminize işlenir. İşlem ücretleri iade edilmez. Ücretsiz dönem sonrasındaki iptaller için iptal politikamıza göre kısmi iadeler uygulanır.',
    'purchase.important.title': 'Önemli Bilgiler',
    'purchase.important.point1': 'Check-in sırasında geçerli kimlik veya pasaport gereklidir',
    'purchase.important.point2': 'Minimum yaş gereksinimi: 18 yaş',
    'purchase.important.point3': 'Evcil hayvanlar önceden onay ile kabul edilir (ek ücret uygulanabilir)',
    'purchase.updated': 'Son güncelleme',
    'purchase.updateDate': 'Ocak 2025',
    
    // Loyalty Program
    'loyalty.hero.title': 'Orbi Ödül Programı',
    'loyalty.hero.subtitle': 'Her konaklamayla puan kazanın ve özel avantajların kilidini açın',
    'loyalty.hero.cta': 'Şimdi Katılın - Ücretsiz',
    'loyalty.howItWorks.title': 'Nasıl Çalışır',
    'loyalty.howItWorks.subtitle': 'Üç basit adımda ödül kazanmaya başlayın',
    'loyalty.step1.title': 'Hesap Oluşturun',
    'loyalty.step1.desc': 'Ücretsiz kaydolun ve hemen kazanmaya başlayın',
    'loyalty.step2.title': 'Puan Kazanın',
    'loyalty.step2.desc': 'Harcanan her lari için 10 puan kazanın',
    'loyalty.step3.title': 'Ödülleri Kullanın',
    'loyalty.step3.desc': 'Puanlarınızı indirimler ve özel ayrıcalıklar için kullanın',
    'loyalty.benefits.title': 'Üyelik Avantajları',
    'loyalty.benefits.subtitle': 'Değerli üyelerimiz için özel avantajlar',
    'loyalty.benefit1': 'Müsait olduğunda erken giriş ve geç çıkış',
    'loyalty.benefit2': 'Ücretsiz oda yükseltmesi (müsaitliğe bağlı)',
    'loyalty.benefit3': 'Yoğun sezonda öncelikli rezervasyon',
    'loyalty.benefit4': 'Sadece üyelere özel fiyatlar ve promosyonlar',
    'loyalty.benefit5': 'Doğum günü sürprizleri ve yıldönümü hediyeleri',
    'loyalty.testimonials.title': 'Üyelerimiz Ne Diyor',
    'loyalty.testimonial1': 'Sadakat programı harika! Son rezervasyonumda 200 lariden fazla tasarruf ettim ve ücretsiz oda yükseltmesi aldım!',
    'loyalty.testimonial2': 'Üyelik, Batum\'a düzenli gezilerimi çok daha iyi hale getirdi. Ayrıcalıklar gerçek!',
    'loyalty.cta.title': 'Kazanmaya Başlamaya Hazır mısınız?',
    'loyalty.cta.subtitle': 'Bugün binlerce memnun üyeye katılın',
    'loyalty.cta.button': 'Ücretsiz Hesap Oluştur',
    
    // About Us
    'about.hero.title': 'Orbi City Batum Hakkında',
    'about.hero.subtitle': 'Karadeniz kıyısında unutulmaz deneyimlere açılan kapınız',
    'about.story.title': 'Hikayemiz',
    'about.story.p1': 'Orbi City Batum, Gürcistan\'ın muhteşem Karadeniz kıyısında modern aparthotel yaşamının zirvesini temsil eder. Kuruluşumuzdan bu yana, misafirlerimize lüks, konfor ve otantik Gürcü konukseverliğinin eşsiz bir karışımını sunmaya kendimizi adadık.',
    'about.story.p2': 'Batum\'un kalbinde, tertemiz plajdan sadece 50 metre ve şehrin ana turistik yerlerine yürüme mesafesinde stratejik olarak konumlanmış, hem tatil hem de iş seyahatçileri için mükemmel bir üs sunuyoruz.',
    'about.story.p3': 'Mükemmelliğe olan bağlılığımız her detayda yansır - nefes kesici deniz manzaralı özenle tasarlanmış apartmanlarımızdan dünya standartlarında olanaklarımıza ve kişiselleştirilmiş concierge hizmetlerimize.',
    'about.mission.title': 'Misyonumuz',
    'about.mission.desc': 'Her misafire beklentileri aşan olağanüstü bir deneyim sunmak, ev konforunu beş yıldızlı lüks ve otantik Gürcü sıcaklığıyla birleştirmek.',
    'about.vision.title': 'Vizyonumuz',
    'about.vision.desc': 'Karadeniz kıyısında önde gelen aparthotel destinasyonu olarak tanınmak, konaklama mükemmelliği için standartları belirlemek ve misafirlerimiz için kalıcı anılar yaratmak.',
    'about.values.title': 'Temel Değerlerimiz',
    'about.values.subtitle': 'Yaptığımız her şeye yön veren ilkeler',
    'about.value1.title': 'Misafir Odaklı Mükemmellik',
    'about.value1.desc': 'Aldığımız her karar misafirlerimizin memnuniyetini ve konforunu ön planda tutar',
    'about.value2.title': 'Taviz Vermeyen Kalite',
    'about.value2.desc': 'Hizmetimizin her yönünde en yüksek standartları koruyoruz',
    'about.value3.title': 'Yenilik ve Büyüme',
    'about.value3.desc': 'Modern gezginlerin ihtiyaçlarını karşılamak ve aşmak için sürekli gelişiyoruz',
    'about.stat1': 'Lüks Apartman',
    'about.stat2': 'Mutlu Misafir',
    'about.stat3': 'Misafir Puanı',
    'about.stat4': 'Hizmet',
    'about.gallery.title': 'Orbi City\'yi Deneyimleyin',
    
    // Apartment Detail
    'apartmentDetail.notFound': 'Apartman bulunamadı',
    'apartmentDetail.backToList': 'Apartmanlara Dön',
    'apartmentDetail.description': 'Açıklama',
    'apartmentDetail.booking': 'Rezervasyon',
    'apartmentDetail.watchVideos': 'Videoları İzle',
    
    // YouTube Videos
    'youtubeVideos.title': 'Video Galerisi',
    'youtubeVideos.subtitle': 'Videolarımız aracılığıyla Orbi City Batum\'u keşfedin',
    'youtubeVideos.breadcrumb': 'Videolar',
    'youtubeVideos.error': 'Videolar şu anda yüklenemiyor. Lütfen daha sonra tekrar deneyin.',
    'youtubeVideos.noVideos': 'Video mevcut değil',
    'youtubeVideos.noDescription': 'Daha fazla bilgi için bu videoyu izleyin',
    'youtubeVideos.watchNow': 'İzle',
    'youtubeVideos.featured': 'Öne Çıkan',
    'youtubeVideos.noVideosInCategory': 'Bu kategoride henüz video yok',
    'youtubeVideos.category.all': 'Tüm Videolar',
    'youtubeVideos.category.propertyTours': 'Tesis Turları',
    'youtubeVideos.category.testimonials': 'Görüşler',
    'youtubeVideos.category.areaGuide': 'Bölge Rehberi',
    'youtubeVideos.category.amenities': 'Olanaklar',
  },
  uk: {
    // Navigation
    'nav.home': 'Головна',
    'nav.rooms': 'Номери',
    'nav.amenities': 'Зручності',
    'nav.location': 'Розташування',
    'nav.reviews': 'Відгуки',
    'nav.contact': 'Контакти',
    'nav.bookNow': 'Забронювати',
    'nav.videos': 'Відео',
    'nav.apartments': 'Апартаменти',
    'nav.loyalty': 'Бонуси',
    'nav.about': 'Про нас',
    
    // Index Videos Section
    'index.videos.title': 'Ознайомтеся з нашими турами по об\'єктах',
    'index.videos.subtitle': 'Дивіться наші останні відео, що демонструють красу та розкіш Orbi City Батумі',
    'index.videos.viewAll': 'Дивитися всі відео',
    
    // Hero
    'hero.title': 'Ваш ідеальний приморський відпочинок',
    'hero.subtitle': 'Розкішні апартаменти з видом на море в серці Батумі',
    'hero.bookNowPayLater': 'ЗАБРОНЮЙТЕ ЗАРАЗ / СПЛАТІТЬ ПІЗНІШЕ',
    'hero.whatsapp': 'WhatsApp',
    
    // Booking Widget
    'booking.title': 'Перевірити наявність',
    'booking.selectDate': 'Оберіть дату',
    'booking.checkIn': 'Заїзд',
    'booking.checkOut': 'Виїзд',
    'booking.guests': 'Гості',
    'booking.checkAvailability': 'Перевірити наявність',
    
    // Rooms
    'rooms.title': 'Знайдіть ваш ідеальний простір',
    'rooms.subtitle': 'Кожен апартамент ретельно спроектований для створення неперевершеного досвіду',
    'rooms.suite': 'Люкс з видом на море',
    'rooms.suiteDesc': 'Елегантний люкс із захоплюючими видами на море, ідеальний для пар або індивідуальних мандрівників',
    'rooms.deluxe': 'Делюкс люкс з видом на море',
    'rooms.deluxeDesc': 'Більш просторий та розкішний люкс з покращеними зручностями та першокласним видом на море',
    'rooms.superior': 'Суперіор люкс з видом на море',
    'rooms.superiorDesc': 'Преміум люкс з окремою житловою зоною та найкращими панорамними видами на море',
    'rooms.family': 'Суперіор сімейний люкс',
    'rooms.familyDesc': 'Просторий люкс з кількома кімнатами, ідеальний для сімей або груп',
    'rooms.twobed': 'Двокімнатний панорамний люкс',
    'rooms.twobedDesc': 'Вершина розкоші. Просторий люкс з двома спальнями та приголомшливою панорамною терасою',
    'rooms.viewDetails': 'Детальніше',
    'rooms.bookNow': 'Забронювати',
    'rooms.from': 'Від',
    'rooms.night': '/ніч',
    'rooms.size': 'Площа',
    'rooms.guests': 'Гостей',
    'rooms.watchVideo': 'Дивитися тур по об\'єкту',
    
    // Amenities
    'amenities.title': 'Зручності світового класу',
    'amenities.subtitle': 'Все, що потрібно для ідеального відпочинку',
    'amenities.seaView': 'Вид на море',
    'amenities.fountains': 'Поруч з фонтанами',
    'amenities.kitchen': 'Повноцінна кухня',
    'amenities.reception': 'Рецепція 24/7',
    'amenities.pool': 'Басейн',
    'amenities.parking': 'Парковка',
    'amenities.wifi': 'Швидкісний WiFi',
    'amenities.ac': 'Кондиціонер',
    'amenities.housekeeping': 'Прибирання номерів',
    'amenities.security': 'Охорона 24/7',
    'amenities.concierge': 'Консьєрж-сервіс',
    'amenities.restaurant': 'Ресторан',
    
    // Location
    'location.title': 'Преміальне розташування в Батумі',
    'location.subtitle': 'У кількох кроках від Чорного моря та головних визначних пам\'яток',
    'location.beach': 'Пляж Чорного моря',
    'location.beachDist': '50 метрів',
    'location.fountains': 'Співаючі фонтани',
    'location.fountainsDist': '100 метрів',
    'location.airport': 'Аеропорт Батумі',
    'location.airportDist': '5 кілометрів',
    
    // Reviews
    'reviews.title': 'Відгуки гостей',
    'reviews.subtitle': 'Що кажуть про нас наші гості',
    'reviews.rating': 'Рейтинг гостей',
    'reviews.review1': 'Приголомшливі види на Чорне море! Апартаменти були розкішними, а персонал неймовірно привітним.',
    'reviews.review2': 'Ідеальне розташування поруч з пляжем та фонтанами. Апартаменти були бездоганно чистими та добре обладнаними.',
    'reviews.review3': 'Дивовижний досвід! Вид на море з нашого балкону був захоплюючим. Дуже рекомендую!',
    
    // CTA
    'cta.title': 'Готові відчути розкіш біля моря?',
    'cta.subtitle': 'Забронюйте ваші ідеальні апартаменти сьогодні',
    'cta.button': 'Забронювати проживання',
    
    // Footer
    'footer.description': 'Розкішні апартаменти з обслуговуванням у серці Батумі, Грузія. У кількох кроках від Чорного моря.',
    'footer.quickLinks': 'Швидкі посилання',
    'footer.contact': 'Зв\'яжіться з нами',
    'footer.phone': 'Телефон',
    'footer.email': 'Email',
    'footer.address': 'Адреса',
    'footer.followUs': 'Підписуйтесь',
    'footer.rights': '© 2025 Orbi City Батумі. Усі права захищені.',
    
    // Apartments Page
    'apartments.hero.title': 'Розкішні апартаменти в Батумі',
    'apartments.hero.subtitle': 'Відкрийте для себе вишукану колекцію апартаментів з видом на море, кожен з яких створений для забезпечення максимального комфорту та вишуканості. Від затишних люксів до просторих сімейних апартаментів.',
    'apartments.section.title': 'Знайдіть ваш ідеальний простір',
    'apartments.section.subtitle': 'Кожен апартамент ретельно спроектований для створення неперевершеного досвіду. Вивчіть наші пропозиції та знайдіть те, що підходить саме вам.',
    'apartments.sqm': 'м²',
    'apartments.guests': 'Гостей',
    'apartments.bed': 'Ліжко',
    'apartments.beds': 'Ліжок',
    'apartments.sofaBed': 'Диван-ліжко',
    'apartments.bath': 'Ванна',
    'apartments.baths': 'Ванних',
    'apartments.bidet': 'Біде',
    'apartments.keyFeatures': 'Ключові особливості',
    'apartments.bookNow': 'Забронювати / Сплатити пізніше',
    'apartments.checkAvailability': 'Перевірити наявність',
    
    // Suite
    'apartments.suite.title': 'Люкс з видом на море',
    'apartments.suite.desc': 'Елегантний люкс із захоплюючими панорамними видами на Чорне море. Ідеально підходить для пар або індивідуальних мандрівників, які шукають спокійний відпочинок з сучасними зручностями та вишуканим дизайном. Прокидайтеся під приголомшливі сходи сонця над морем з вашого особистого балкону.',
    'apartments.suite.feature1': 'Особистий балкон з видом на море',
    'apartments.suite.feature2': 'Повністю обладнана міні-кухня',
    'apartments.suite.feature3': 'Швидкісний WiFi',
    'apartments.suite.feature4': 'Розумний клімат-контроль',
    'apartments.suite.feature5': '55" Smart TV зі стрімінгом',
    'apartments.suite.feature6': 'Ліжко King Size з преміум постільною білизною',
    
    // Deluxe
    'apartments.deluxe.title': 'Делюкс люкс з видом на море',
    'apartments.deluxe.desc': 'Більш просторий та розкішний люкс з покращеними зручностями та першокласними видами на море. Створений для вибагливих гостей, які цінують увагу до деталей та комфорт. Окрема вітальня надає додатковий простір для відпочинку та розваг.',
    'apartments.deluxe.feature1': 'Просторий балкон з видом на море',
    'apartments.deluxe.feature2': 'Окрема вітальня та обідня зона',
    'apartments.deluxe.feature3': 'Повноцінна кухня з преміум технікою',
    'apartments.deluxe.feature4': 'Безкоштовний швидкісний WiFi',
    'apartments.deluxe.feature5': 'Двозонний клімат-контроль',
    'apartments.deluxe.feature6': 'Преміум розважальна система',
    
    // Superior
    'apartments.superior.title': 'Суперіор люкс з видом на море',
    'apartments.superior.desc': 'Наш преміум люкс з окремою спальнею, розкішною житловою зоною та найкращими панорамними видами на Чорне море. Ідеально підходить для гостей, які бажають додаткового простору та преміум зручностей. Кутове розташування забезпечує максимальне природне освітлення та вражаючі види на океан.',
    'apartments.superior.feature1': 'Кутові панорамні види на море',
    'apartments.superior.feature2': 'Одна окрема спальня',
    'apartments.superior.feature3': 'Простора обідня зона',
    'apartments.superior.feature4': 'Сучасна повноцінна ванна',
    'apartments.superior.feature5': 'Дизайнерська міні-кухня',
    'apartments.superior.feature6': 'Люксові приналежності для ванної',
    'apartments.superior.feature7': 'Ліжко King зі стельовими дзеркалами',
    
    // Family
    'apartments.family.title': 'Суперіор сімейний люкс з видом на море',
    'apartments.family.desc': 'Просторий люкс з двома спальнями та двома ванними кімнатами, ідеально підходить для сімей або груп до 6 гостей. Насолоджуйтесь комфортом та приватністю з окремими спальними зонами, зберігаючи зв\'язок у просторій вітальні. Ідеально для створення незабутніх спогадів з близькими.',
    'apartments.family.feature1': 'Просторий особистий балкон',
    'apartments.family.feature2': 'Дві окремі спальні',
    'apartments.family.feature3': 'Дві повноцінні ванні з біде',
    'apartments.family.feature4': 'Повноцінна кухня та обідня зона',
    'apartments.family.feature5': 'Пральна машина в номері',
    'apartments.family.feature6': 'Пріоритетні послуги консьєржа',
    'apartments.family.feature7': 'Ліжка King з преміум функціями',
    
    // Two Bedroom
    'apartments.twobed.title': 'Двокімнатний панорамний люкс',
    'apartments.twobed.desc': 'Вершина розкішного життя в Батумі. Цей просторий люкс включає дві головні спальні та вражаючу 270° панорамну терасу з безперервними видами на Чорне море. Ідеально підходить для сімей або груп, які шукають максимум простору, комфорту та захоплюючих краєвидів.',
    'apartments.twobed.feature1': '270° панорамна тераса з видом на океан',
    'apartments.twobed.feature2': '2 головні спальні з власними ванними',
    'apartments.twobed.feature3': '2 розкладних дивани-ліжка',
    'apartments.twobed.feature4': '2 ліжка King зі стельовими дзеркалами',
    'apartments.twobed.feature5': 'Гурманська кухня',
    'apartments.twobed.feature6': 'Дизайнерські люксові меблі',
    'apartments.twobed.feature7': 'Неперевершені види на море та місто',
    
    // Location Page
    'location.page.title': 'Преміальне розташування на березі моря',
    'location.page.subtitle': 'Ідеально розташований у серці Батумі, у кількох кроках від Чорного моря та головних визначних пам\'яток. Відчуйте найкраще від прибережного життя з неперевершеною зручністю.',
    
    // Amenities
    'amenities.hero.title': 'Зручності світового класу',
    'amenities.hero.subtitle': 'Все, що потрібно для незабутнього відпочинку',
    'amenities.premium.title': 'Преміальні об\'єкти',
    'amenities.premium.subtitle': 'Насолоджуйтесь нашими ексклюзивними зручностями, створеними для вашого максимального комфорту',
    'amenities.standard.title': 'Основні послуги',
    'amenities.standard.subtitle': 'Усі зручності, які ви очікуєте, і навіть більше',
    'amenities.pool.title': 'Басейн та спа',
    'amenities.pool.desc': 'Розслабтеся в нашому приголомшливому басейні з панорамними видами на море',
    'amenities.fitness.title': 'Фітнес-центр',
    'amenities.fitness.desc': 'Сучасне спортивне обладнання для ваших тренувань',
    'amenities.spa.title': 'Велнес та спа',
    'amenities.spa.desc': 'Відновіть сили з нашими професійними спа-процедурами',
    'amenities.restaurant.title': 'Вишуканий ресторан',
    'amenities.restaurant.desc': 'Насолоджуйтесь вишуканою кухнею від шеф-кухарів світового класу',
    'amenities.cafe.title': 'Кафе на березі моря',
    'amenities.cafe.desc': 'Насолоджуйтесь кавою та легкими закусками з приголомшливими видами на океан',
    'amenities.bar.title': 'Бар на даху',
    'amenities.bar.desc': 'Розслабтеся з преміальними коктейлями та захоплюючими видами заходу сонця',
    'amenities.wifi.title': 'Швидкісний WiFi',
    'amenities.wifi.desc': 'Безкоштовний швидкісний інтернет на всій території',
    'amenities.security.title': 'Охорона 24/7',
    'amenities.security.desc': 'Цілодобова охорона та відеоспостереження для вашого спокою',
    'amenities.reception.title': 'Рецепція 24/7',
    'amenities.reception.desc': 'Наша команда консьєржів завжди до ваших послуг',
    'amenities.parking.title': 'Охоронювана парковка',
    'amenities.parking.desc': 'Безкоштовна парковка з цілодобовою охороною',
    'amenities.ac.title': 'Клімат-контроль',
    'amenities.ac.desc': 'Індивідуальний кондиціонер у кожному апартаменті',
    'amenities.concierge.title': 'Консьєрж-сервіс',
    'amenities.concierge.desc': 'Персоналізована допомога для всіх ваших потреб',
    
    // Purchase Conditions
    'purchase.hero.title': 'Умови придбання та бронювання',
    'purchase.hero.subtitle': 'Чіткі, прозорі умови для вашого спокою',
    'purchase.breadcrumb': 'Умови придбання',
    'purchase.payment.title': 'Умови оплати',
    'purchase.payment.content': 'Ми приймаємо банківські перекази, кредитні/дебетові картки та готівку. Повна оплата вимагається при заселенні, якщо не узгоджено заздалегідь. Ми пропонуємо гнучкі плани оплати для тривалого проживання. Приймаються всі основні кредитні картки.',
    'purchase.cancellation.title': 'Політика скасування',
    'purchase.cancellation.content': 'Безкоштовне скасування за 7 днів до прибуття. Скасування протягом 7 днів тягне за собою 50% комісію. Неявка призводить до повної оплати. Ми розуміємо, що плани змінюються - зв\'яжіться з нами для особливих обставин.',
    'purchase.deposit.title': 'Страхова застава',
    'purchase.deposit.content': 'При заселенні може вимагатися повернення страхової застави. Сума залежить від типу апартаментів. Застави повністю повертаються після перевірки, зазвичай протягом 3-5 робочих днів.',
    'purchase.refund.title': 'Політика повернення коштів',
    'purchase.refund.content': 'Повернення обробляються протягом 14 робочих днів на ваш початковий спосіб оплати. Комісія за обробку не повертається. Для скасувань поза безкоштовним періодом застосовується часткове повернення згідно з нашою політикою скасування.',
    'purchase.important.title': 'Важлива інформація',
    'purchase.important.point1': 'При заселенні вимагається дійсне посвідчення особи або паспорт',
    'purchase.important.point2': 'Мінімальний вік: 18 років',
    'purchase.important.point3': 'Домашні тварини дозволені з попереднім погодженням (може стягуватися додаткова плата)',
    'purchase.updated': 'Останнє оновлення',
    'purchase.updateDate': 'Січень 2025',
    
    // Loyalty Program
    'loyalty.hero.title': 'Програма винагород Orbi',
    'loyalty.hero.subtitle': 'Заробляйте бали з кожним проживанням та отримуйте ексклюзивні переваги',
    'loyalty.hero.cta': 'Приєднуйтесь - це безкоштовно',
    'loyalty.howItWorks.title': 'Як це працює',
    'loyalty.howItWorks.subtitle': 'Почніть заробляти винагороди за три прості кроки',
    'loyalty.step1.title': 'Створіть обліковий запис',
    'loyalty.step1.desc': 'Зареєструйтесь безкоштовно та почніть заробляти одразу',
    'loyalty.step2.title': 'Заробляйте бали',
    'loyalty.step2.desc': 'Отримуйте 10 балів за кожен витрачений ларі',
    'loyalty.step3.title': 'Використовуйте винагороди',
    'loyalty.step3.desc': 'Використовуйте ваші бали для знижок та ексклюзивних привілеїв',
    'loyalty.benefits.title': 'Переваги членства',
    'loyalty.benefits.subtitle': 'Ексклюзивні переваги для наших цінних учасників',
    'loyalty.benefit1': 'Ранній заїзд та пізній виїзд за наявності можливості',
    'loyalty.benefit2': 'Безкоштовне підвищення категорії номера (за наявності можливості)',
    'loyalty.benefit3': 'Пріоритетне бронювання у високий сезон',
    'loyalty.benefit4': 'Ексклюзивні тарифи та акції лише для членів',
    'loyalty.benefit5': 'Сюрпризи на день народження та ювілей',
    'loyalty.testimonials.title': 'Що кажуть наші учасники',
    'loyalty.testimonial1': 'Програма лояльності чудова! При останньому бронюванні я зекономив понад 200 ларі та отримав безкоштовне підвищення номера!',
    'loyalty.testimonial2': 'Членство зробило мої регулярні поїздки до Батумі набагато кращими. Привілеї справжні!',
    'loyalty.cta.title': 'Готові почати заробляти?',
    'loyalty.cta.subtitle': 'Приєднуйтесь до тисяч задоволених учасників сьогодні',
    'loyalty.cta.button': 'Створити безкоштовний обліковий запис',
    
    // About Us
    'about.hero.title': 'Про Orbi City Батумі',
    'about.hero.subtitle': 'Ваші ворота до незабутніх вражень на узбережжі Чорного моря',
    'about.story.title': 'Наша історія',
    'about.story.p1': 'Orbi City Батумі представляє вершину сучасного життя апартготелю на приголомшливому чорноморському узбережжі Грузії. З моменту заснування ми присвятили себе наданню гостям неперевершеного поєднання розкоші, комфорту та автентичної грузинської гостинності.',
    'about.story.p2': 'Стратегічно розташований у серці Батумі, лише за 50 метрів від чистого пляжу та в пішій доступності від головних визначних пам\'яток міста, ми пропонуємо ідеальну базу як для відпочинку, так і для ділових мандрівників.',
    'about.story.p3': 'Наша відданість досконалості відображається в кожній деталі - від наших ретельно спроектованих апартаментів із захоплюючими видами на море до зручностей світового класу та персоналізованих консьєрж-послуг.',
    'about.mission.title': 'Наша місія',
    'about.mission.desc': 'Надати кожному гостю виняткові враження, що перевершують очікування, поєднуючи домашній комфорт з п\'ятизірковою розкішшю та автентичним грузинським теплом.',
    'about.vision.title': 'Наше бачення',
    'about.vision.desc': 'Бути визнаним як провідний апартготель на узбережжі Чорного моря, встановлюючи стандарти гостинності та створюючи незабутні спогади для наших гостей.',
    'about.values.title': 'Наші основні цінності',
    'about.values.subtitle': 'Принципи, які спрямовують все, що ми робимо',
    'about.value1.title': 'Орієнтація на гостя',
    'about.value1.desc': 'Кожне наше рішення ставить задоволення та комфорт гостей на перше місце',
    'about.value2.title': 'Якість без компромісів',
    'about.value2.desc': 'Ми підтримуємо найвищі стандарти в усіх аспектах нашого сервісу',
    'about.value3.title': 'Інновації та розвиток',
    'about.value3.desc': 'Постійно розвиваємося для задоволення потреб сучасних мандрівників',
    'about.stat1': 'Люксових апартаментів',
    'about.stat2': 'Задоволених гостей',
    'about.stat3': 'Рейтинг гостей',
    'about.stat4': 'Сервіс',
    'about.gallery.title': 'Відчуйте Orbi City',
    
    // Apartment Detail
    'apartmentDetail.notFound': 'Апартамент не знайдено',
    'apartmentDetail.backToList': 'Назад до апартаментів',
    'apartmentDetail.description': 'Опис',
    'apartmentDetail.booking': 'Бронювання',
    'apartmentDetail.watchVideos': 'Дивитися відео',
    
    // YouTube Videos
    'youtubeVideos.title': 'Відеогалерея',
    'youtubeVideos.subtitle': 'Відкрийте для себе Orbi City Батумі через наші відео',
    'youtubeVideos.breadcrumb': 'Відео',
    'youtubeVideos.error': 'Не вдається завантажити відео в цей момент. Будь ласка, спробуйте пізніше.',
    'youtubeVideos.noVideos': 'Відео недоступні',
    'youtubeVideos.noDescription': 'Перегляньте це відео, щоб дізнатися більше',
    'youtubeVideos.watchNow': 'Дивитися',
    'youtubeVideos.featured': 'Рекомендоване',
    'youtubeVideos.noVideosInCategory': 'У цій категорії поки немає відео',
    'youtubeVideos.category.all': 'Усі відео',
    'youtubeVideos.category.propertyTours': 'Тури по об\'єктах',
    'youtubeVideos.category.testimonials': 'Відгуки',
    'youtubeVideos.category.areaGuide': 'Путівник',
    'youtubeVideos.category.amenities': 'Зручності',
  },
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem('language') as Language;
    return saved || detectBrowserLanguage();
  });

  useEffect(() => {
    localStorage.setItem('language', language);
    document.documentElement.lang = language === 'ka' ? 'ka' : language === 'ru' ? 'ru' : language === 'tr' ? 'tr' : language === 'uk' ? 'uk' : 'en';
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key] || translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
};
